// Novena a São José - 19 de Março
export const novenaSaoJose19Marco = {
  saintName: "São José",
  novenaTitle: "Novena a São José - 19 de Março",
  description: "Novena em honra a São José, esposo de Maria Santíssima e pai nutrício de Jesus, celebrada em preparação para sua festa em 19 de março.",
  image: "https://iili.io/fj7jrtj.png",
  initialPrayer: `<div class="initial-prayer-text"><div class="prayer-block"><p>Lembrai-vos, ó puríssimo Esposo da Virgem Maria, ó meu doce Protetor São José, que jamais se ouviu dizer que alguém tivesse invocado vossa proteção, implorando vosso socorro e não fosse por vós consolado.</p><p>Com grande confiança, venho a vossa presença recomendar-me fervorosamente a vós. Não desprezeis as minhas súplicas, ó pai adotivo do Redentor, mas dignai-vos acolhê-la piedosamente. Assim seja.</p><p class="mt-4"><b>ANT.</b> José, filho de Davi, não temas receber Maria, vossa Esposa Santíssima, em vossa companhia, porque o que ela leva em suas puríssimas entranhas é obra do Espírito Santo.</p><p class="mt-2">V. Rogai por nós, José santíssimo.<br>R. Para que sejamos dignos das promessas de Cristo.</p></div></div>`,
  finalPrayer: `<div class="final-prayer-text"><h4 class="section-title">Oração final para todos os dias</h4><div class="prayer-block"><p>Lembrai-vos, ó puríssimo Esposo da Virgem Maria, ó meu doce Protetor São José, que jamais se ouviu dizer que alguém tivesse invocado vossa proteção, implorando vosso socorro e não fosse por vós consolado.</p><p>Com grande confiança, venho a vossa presença recomendar-me fervorosamente a vós. Não desprezeis as minhas súplicas, ó pai adotivo do Redentor, mas dignai-vos acolhê-la piedosamente. Assim seja.</p><p class="mt-4"><b>ANT.</b> José, filho de Davi, não temas receber Maria, vossa Esposa Santíssima, em vossa companhia, porque o que ela leva em suas puríssimas entranhas é obra do Espírito Santo.</p><p class="mt-2">V. Rogai por nós, José santíssimo.<br>R. Para que sejamos dignos das promessas de Cristo.</p><p class="mt-4 font-semibold">Oremos: Ó Jesus, que por uma inefável providência, dignastes-Vos escolher o bem-aventurado esposo de Vossa Mãe Santíssima; concedei-nos que aquele mesmo que veneramos como protetor, mereçamos tê-lo no céu por nosso intercessor. Vós que viveis e reinais por todos os séculos dos séculos. Amém.</p><p class="mt-4 italic">Pede-se agora a graça que necessita conseguir.</p><p class="mt-2">Para melhor alcançar as graças pedidas, rezaremos sete Pais-Nossos, sete Ave-Marias e sete Glórias ao Pai em honra das alegrias e dores do glorioso patriarca.</p></div></div>`,
  days: [
    {
      day: "Primeiro dia",
      title: "Primeiro dia",
      content: `<div class="day-specific-content"><p>Dou graças à Santíssima Trindade, Santíssimo São José, pelos muitos privilégios, méritos e virtudes com que vos enriqueceu e, principalmente, pelo grande e singularíssimo mérito a poucos concedido de ter sido santificado no ventre de vossa mãe e confirmado em graça. Que alegria para vosso coração ver-vos livre do pecado, que é a única coisa que desagrada a Deus Filho, que vos chamava de pai! Que graças destes à Trindade Beatífica por esse tão assinalado privilégio! Eu vos felicito, com todo o meu coração, pela inocência incomparável que tivestes desde antes de nascer e pela graça a amizade particular com que o mesmo Deus vos distinguiu.</p><p class="mt-4">Por esse privilégio e pela grande alegria que Ele vos causou, suplico-vos, ó meu querido pai, que me alcanceis de Deus um grande ódio ao pecado, grande amor às virtudes e à minha salvação eterna. E como creio que a graça que desejo conseguir nesta novena será benéfica à minha salvação, tenho inteira confiança de que a alcançareis por vossa poderosíssima intercessão; todavia, se minha oração não for bem dirigida, endireitai-a e rogai ao boníssimo Deus por mim. Amém.</p></div>`
    },
    {
      day: "Segundo dia",
      title: "Segundo dia",
      content: `<div class="day-specific-content"><p>Que felicidade a vossa, meu glorioso protetor, serdes escolhido milagrosamente para esposo da Imaculada Maria!</p><p>Alegro-me convosco pela satisfação imensa que experimentastes, naquele dia feliz, quando associastes vossa sorte à da Mãe de Jesus Cristo. Que admiração vos teriam os santos anjos, por serdes o sustentáculo da Mãe do Verbo encarnado e, por esse mesmo motivo, também protetor do Filho de Deus!</p><p>Uno meus louvores aos que, nesse dia, vos dariam os anjos do céu e, de todo o meu coração, vos felicito por vos ter sido dada de presente a Rainha dos Anjos, e pelo zelo que se dedicou a vosso serviço. Que transbordante felicidade! Que maravilha terdes por companheira aquela que trouxe o Filho de Deus em Seu seio sagrado!</p><p>Que felicidade terdes, para vosso consolo nas penas, a Consoladora dos aflitos, para conselheira nas dificuldades a sapientíssima Mãe de Jesus Cristo e para modelo nas virtudes, aquela que é o espelho sem mancha, a Majestade Divina e a imagem da bondade de Deus! Por esse favor e felicidade tão grandes, peço-vos, poderosíssimo José, a amizade e a graça de Deus, a proteção e o amparo constantes de Maria Santíssima. Amém.</p></div>`
    },
    {
      day: "Terceiro dia",
      title: "Terceiro dia",
      content: `<div class="day-specific-content"><p>Que pena tão amarga devíeis ter sentido em vosso coração, José gloriosíssimo, quando, em vossa humildade, julgastes dever separar-vos de vossa esposa Maria! Separar-vos de Maria, que tanto amáveis e que correspondia a vosso amor com amor puro e sincero.</p><p>Confraternizo-me convosco por aqueles momentos de sofrimento e por essa amarga provação que o Senhor vos permitiu! Por caridade, ficastes ao lado da Mãe do Unigênito Filho de Deus. Maria vos pertenceu e amou sempre no amor de Deus. Em Seu infinito poder, Deus fez nela maravilhas de Seu Divino Amor. Fostes a maior testemunha das grandiosidades operadas em Maria. Ela é o jardim de Deus e o paraíso onde o Filho tem seu recreio, e vós José, fostes o anjo da guarda desse jardim, o depositário desse eterno tesouro.</p><p>São José, aceitai sinceras felicitações pela parte ativa que Deus vos concedeu o mistério da Encarnação, e pela sujeição de Jesus e de Sua Santíssima Mãe às vossas ordens.</p><p>Por essa grande alegria e também pelos méritos da tristeza que a precedeu, suplico-vos, meu pai querido, que me alcanceis de Deus o conhecimento de Jesus Cristo e a graça de conservar uma fé tão viva em todos os seus mistérios, que esteja pronto a antes morrer que duvidar deles; alcançai-me, outrossim, a graça que, nesta novena, pretendo conseguir, se for para maior glória de Deus e bem de minha alma. Amém.</p></div>`
    },
    {
      day: "Quarto dia",
      title: "Quarto dia",
      content: `<div class="day-specific-content"><p>Esposo castíssimo da Mãe do Unigênito Filho de Deus, uno-me a vós na tristeza que experimentastes em Belém, quando lá chegando, depois de penosa viagem, vistes vossa venerada esposa Maria e o Salvador do mundo, que ela levava em suas entranhas, desconhecidos e repelidos de todas as casas e pousadas.</p><p>Ó meu querido José, como conhecestes então que o mundo não é amigo de Cristo, e que é impossível servir juntamente dois senhores tão inimigos e contrários! Dai-me a Jesus, que tanta alegria vos causou em Seu nascimento.</p><p>As vozes dos anjos dizendo "paz na terra aos homens de boa vontade" são principalmente dirigidas a vós. Aceitai meus louvores pelo muito amor que Jesus vos manifestou, escolhendo-vos para Seu pai nutrício e para seu poderoso defensor e amparo.</p><p>Permiti-me, gloriosíssimo e poderosíssimo santo, chegar aonde vós estais, perto de Jesus, contemplar Sua santidade divina e esplendor. Pedi a Jesus que Ele me dê as graças recebidas pelos pastores e reis que foram adorá-Lo no presépio; pedi-Lhe também as graças que desejo conseguir nesta novena, se forem para maior glória de Deus e salvação de minha alma. Amém.</p></div>`
    },
    {
      day: "Quinto dia",
      title: "Quinto dia",
      content: `<div class="day-specific-content"><p>Que grande dor sofrestes, nosso querido São José, quando vistes derramar-se o preciosíssimo Sangue de Cristo na circuncisão! Por que teria, esse infante divino, de sofrer assim, poucos dias depois de ter nascido? Ah! Sendo Jesus a perfeição em pessoa, certamente que foi pelos nossos pecados esse padecer.</p><p>São José, dai-me a conhecer o preço do Sangue de Jesus para que nunca deixe perder a menor gota; e que esse sangue, caindo abundantemente sobre minha alma, lave-me e purifique inteiramente. Permiti São José, que, para eu conseguir graça tão importante, aproxime-me mais de vós para ouvir atento e obedecer aos ensinamentos do Divino Mestre e receber as bênçãos e graças que dele emanam e que, por bondade divina, passam por vossas sagradas mãos.</p><p>Vossas mãos sagradas amparam Jesus, o Salvador do mundo, que tira os pecados dos homens! São José, que alegria a vossa, quando destes ao Salvador o nome de Jesus, sabendo que esse nome, a própria felicidade, é a chave que nos abre a porta do céu!</p><p>Adorador de Cristo, consiga que ele seja para mim Jesus, isto é, meu salvador nesta vida e na eterna.</p><p>Pelo nome adorável, Jesus, peço-vos também as graças que desejo alcançar nesta novena, se forem para maior glória de Deus e para o bem de minha alma. Amém.</p></div>`
    },
    {
      day: "Sexto dia",
      title: "Sexto dia",
      content: `<div class="day-specific-content"><p>Ó meu boníssimo São José, protetor e amparo dos desvalidos, por aquela alegria que experimentou o vosso coração, ouvindo os louvores que os doutores da lei fazem ao Cristo Menino, peço-vos que não vos esqueçais de mim, fazei que Jesus, meu Salvador, seja sempre para mim ocasião de ressurreição. Confraternizo-me convosco, pacienciosíssimo José, pela ferida que em vosso coração fizeram as palavras do Santo Simeão, com que anunciara a Maria que uma espada de dor havia de atravessar Seu delicado e amorosíssimo coração.</p><p>Em tão tremenda ocasião para Maria, vós nem poderíeis remediar essas dores, nem ao menos ser testemunha de tão terrível padecer, para consolar vossa esposa com vossa presença humana na Paixão de Cristo!</p><p>Eu, sim, posso e devo, com minha vida e bons costumes, consolar a Maria, porque culpado por meus pecados, na morte de Jesus e nas dores de Maria, quero e devo evitar e reparar esses pecados.</p><p>Ajudai, José poderosíssimo, minha pobreza espiritual e poucas forças, alcançando-me de Nosso Senhor a graça de nunca ser, por minha culpa, causa das penas de Jesus e das dores de Maria. Alcançai-me também a graça que desejo conseguir rezando esta novena, se for para maior glória de Deus e salvação de minha alma. Amém.</p></div>`
    },
    {
      day: "Sétimo dia",
      title: "Sétimo dia",
      content: `<div class="day-specific-content"><p>São José, permiti que, em espírito, eu vos acompanhe na viagem ao Egito para admirar vossos sacrifícios e imitar vossas virtudes. Tudo fizestes para defender Jesus de tantos perigos, sobretudo da morte.</p><p>Que dor tão grande foi para vosso coração amante ver sofrer Jesus e Maria! Quanta sede devem ter sofrido no deserto os três peregrinos santíssimos!</p><p>Peço-vos humildemente que tireis de mim a sede dos prazeres mundanos e dai-me a fome e a sede de todas as virtudes, principalmente a humildade, a paciência, a mortificação que a minha alma deseja ardentemente possuir. Entristeçam-me as coisas que vos entristecem, amável São José, e saiba eu alegrar-me com as que vos causam alegria.</p><p>Experimente minha alma, conservando-se na graça de Deus, a mesma alegria que experimentou vosso delicado coração, quando, afinal, depois dos transtornos de uma perigosa viagem por ermos desertos, vistes Jesus a salvo e Maria vossa amantíssima esposa segura no novo lar. Assim como vos alegrastes com a queda dos ídolos do Egito, alegra-se meu coração com a queda dos ídolos das afeições desregradas e das paixões desordenadas, de modo que, em tudo e por tudo, agrade a Jesus, à Santíssima Mãe e a vós, meu amável José, que tanto gozais na glória de Deus. Alcançai-me também a graça que desejo conseguir nesta novena, se for para maior glória de Deus. Amém.</p></div>`
    },
    {
      day: "Oitavo dia",
      title: "Oitavo dia",
      content: `<div class="day-specific-content"><p>Confraternizo-me convosco, terníssimo José, por causa das privações a que vistes sujeita vossa amada família, na terra de peregrinação, e pelo mesmo desterro tão meritório, sobretudo para a Mãe do Filho de Deus.</p><p>Uno minhas lágrimas às que derramastes, em vosso coração, pela dureza do exílio e por tudo que faltou a vós, a Maria e a Jesus, no Egito. Vossa família, que é a família de Deus, tão paciente, e eu me queixo de qualquer pequena e insignificante mortificação, ainda que necessária!</p><p>Ó meu querido José, pela alegria imensa que inundou vosso coração quando Jesus, pela primeira vez, deu-vos o doce nome de pai, e pela sujeição com que, pela primeira vez, vos prestou a homenagem de sua obediência, suplico-vos que me ensineis a obedecer aos meus superiores e a sofrer, com paciência e resignação, as provas que a Divina Providência se dignar enviar-me, para purificar-me de meus pecados ou para aumentar meus méritos.</p><p>Alcançai-me também, pela alegria com que voltastes do exílio para morar em Nazaré, a graça com que tanta humildade vos peço nesta novena, se não for em prejuízo de minha salvação. Amém.</p></div>`
    },
    {
      day: "Nono dia",
      title: "Nono dia",
      content: `<div class="day-specific-content"><p>Ó José, chamado por Jesus com o nome de pai, que dor e tormento indizível seria para vosso coração amorosíssimo ter perdido Jesus, com o qual estavam todas as afeições de vossa vida! Que grande aflição sentistes por não ter encontrado o Menino Jesus entre parentes e conhecidos e por ninguém ter dado notícias d'Ele.</p><p>Onde estaria Jesus? Como poderíeis viver se Ele era a vossa alegria de viver? Vós perdestes a Jesus, sem culpa vossa, mas eu perdi-O muitas vezes por culpa própria, por causa de minha malícia e de meus pecados.</p><p>Fazei-me conhecer a Jesus e procurá-Lo com perseverança, ensina-me a obedecê-Lo, ensina-me a adorá-Lo custe o que custar. Consiga-me a graça de que, de hoje em diante, nunca mais eu o perca pelo pecado e que se por infelicidade eu venha a perdê-Lo, nunca tenha sossego até que o encontre novamente pela divina graça.</p><p>Peço-vos esta graça, pela alegria inefável que experimentastes achando a Jesus no templo, ensinando, como Mestre Divino, aos doutores da lei e causando-lhes encanto e admiração com Suas perguntas e respostas.</p><p>Intercedei para que eu esteja sempre em união com Jesus e Sua santa Igreja. Consegui que Jesus esteja sempre em meu coração, com Sua divina caridade, e que, no futuro, eu possa gozar de Sua visão e amizade no céu para sempre.</p><p>Alcançai-me também as graças que vos tenho pedido, todos os dias, durante a novena. Tenho confiança de que, tudo que vos pedi, irei receber do amor de Deus, por vosso intermédio. De agora em diante, com a graça divina, serei divulgador do poder que o Misericordioso Deus vos concede. Amém.</p></div>`
    }
  ]
};
