// Tipo local para evitar importação circular
type SaintOfTheDayData = {
    day: number;
    month: string;
    saints: {
        name: string;
        imageUrl: string;
        imageObjectPosition?: string;
        story: string;
        isMartyr?: boolean;
    }[];
};


// Dados completos dos santos de Março a Setembro
export const santosMarcoSetembro: SaintOfTheDayData[] = [
    // FEVEREIRO
    { day: 1, month: 'Fevereiro', saints: [{ name: 'Santa Brígida', imageUrl: '/images/santa_brigida.png', story: '<h4>Padroeira da Irlanda</h4><p>Santa Brígida de Kildare (451-525) foi uma das maiores santas da Irlanda. Fundou o mosteiro de Kildare, que se tornou um importante centro de evangelização, arte e cultura. Conhecida por sua extraordinária caridade, distribuía alimentos aos pobres e realizava milagres de cura. Ao lado de São Patrício e São Columba, é uma das três padroeiras da Irlanda.</p><p class="mt-4">Sua vida foi marcada pela generosidade sem limites. Conta-se que certa vez deu todo o leite de suas vacas aos pobres, e milagrosamente as vacas produziram o triplo no dia seguinte. Era tão caridosa que chegou a dar a espada de seu pai a um leproso, o que inicialmente causou a ira dele, mas depois o converteu ao ver a fé da filha.</p><p class="mt-4"><b>Oração:</b> Santa Brígida, que vivestes em profunda caridade e amor aos pobres, intercedei por nós para que saibamos partilhar nossos bens e servir aos necessitados com alegria. Amém.</p><p class="mt-2 italic">Santa Brígida, rogai por nós.</p>' }] },
    { day: 2, month: 'Fevereiro', saints: [{ name: 'Apresentação do Senhor', imageUrl: '/images/apresentacao_jesus.png', story: '<h4>Luz das Nações</h4><p>Quarenta dias após o nascimento de Jesus, Maria e José O levaram ao Templo de Jerusalém para apresentá-Lo ao Senhor, conforme a Lei de Moisés. Ali foram recebidos pelo ancião Simeão, que reconheceu no Menino o Messias prometido e proclamou: "Meus olhos viram a tua salvação, luz para iluminar as nações" (Lc 2,30-32).</p><p class="mt-4">A profetisa Ana, de 84 anos, também reconheceu Jesus e deu graças a Deus, falando dEle a todos que esperavam a redenção de Jerusalém. Simeão profetizou a Maria que uma espada de dor traspassaria sua alma, prenunciando os sofrimentos da Paixão.</p><p class="mt-4">Esta festa também é conhecida como "Festa das Candeias" ou "Candelária", pois neste dia são benzidas as velas que serão usadas durante o ano litúrgico, simbolizando Cristo como Luz do mundo. É uma das festas mais antigas do cristianismo, celebrada desde o século IV.</p><p class="mt-4"><b>Oração:</b> Senhor Jesus, luz das nações, iluminai nossos corações e guiai nossos passos no caminho da salvação. Que, como Simeão e Ana, saibamos reconhecer-Vos presente em nossa vida. Amém.</p><p class="mt-2 italic">Luz de Cristo, iluminai-nos.</p>' }] },
    { day: 3, month: 'Fevereiro', saints: [{ name: 'São Brás', imageUrl: '/images/sao-bras.jpg', story: '<h4>Bispo e Mártir - Protetor da Garganta</h4><p>São Brás foi bispo de Sebaste, na Armênia, durante o século IV. Médico de profissão antes de sua conversão, dedicou sua vida ao cuidado espiritual e físico de seu povo. Durante a perseguição do imperador Licínio, retirou-se para uma caverna nas montanhas, onde viveu em oração e penitência.</p><p class="mt-4">Conta-se que os animais selvagens o visitavam e ele os curava de suas enfermidades. Quando foi descoberto e preso por soldados romanos, no caminho para a prisão realizou seu milagre mais famoso: salvou um menino que estava morrendo sufocado com uma espinha de peixe atravessada na garganta. Por este motivo, tornou-se o padroeiro invocado contra males da garganta e doenças respiratórias.</p><p class="mt-4">Na prisão, continuou a realizar curas milagrosas. Uma viúva pobre trouxe-lhe um porco que havia sido salvo por sua bênção. Antes de ser martirizado, prometeu que todos aqueles que invocassem seu nome em suas enfermidades seriam atendidos. Foi torturado com pentes de ferro (usados para cardar lã) e depois decapitado por volta do ano 316.</p><p class="mt-4">A tradição da bênção de São Brás, feita com duas velas cruzadas sobre a garganta, é praticada em sua festa (3 de fevereiro) em muitas igrejas ao redor do mundo. É padroeiro dos médicos, veterinários e de todos que sofrem de doenças da garganta.</p><p class="mt-4"><b>Oração:</b> São Brás, glorioso mártir e bispo, que curaste milagrosamente um menino prestes a morrer sufocado, intercedei por nós junto a Deus. Protegei-nos de todos os males da garganta e de toda enfermidade. Alcançai-nos a saúde do corpo e da alma para que possamos servir a Deus com alegria. Amém.</p><p class="mt-2 italic">São Brás, rogai por nós.</p>', isMartyr: true }] },
    { day: 4, month: 'Fevereiro', saints: [{ name: 'São João de Brito', imageUrl: '/images/sao-joao-brito.png', story: '<h4>Apóstolo da Índia - Mártir da Inculturação</h4><p>São João de Brito nasceu em Lisboa, Portugal, em 1647, numa família nobre ligada à corte real. Aos 15 anos, após curar-se milagrosamente de uma grave doença por intercessão de São Francisco Xavier, decidiu tornar-se jesuíta e missionário. Em 1673, partiu para a Índia, seguindo os passos de seu patrono.</p><p class="mt-4">Chegando à missão de Madurai, no sul da Índia, João de Brito adotou uma estratégia missionária revolucionária: a inculturação radical. Vestiu-se como um "sannyasi" (asceta hindu), adotou o nome de "Arul Anandar" (Mestre da Graça Divina), viveu de esmolas, praticou jejuns rigorosos e caminhou descalço pelas aldeias. Aprendeu o tâmil perfeitamente e adaptou a liturgia católica aos costumes locais, sempre mantendo a integridade da fé.</p><p class="mt-4">Seu método era tão eficaz que converteu milhares de hindus, incluindo membros da casta dos brâmanes. Entre seus convertidos estava Tadiathevan, sobrinho do rajá de Marava, que tinha várias esposas. Quando João de Brito exigiu que ele renunciasse a todas exceto uma para ser batizado, despertou a ira do rajá e dos brâmanes locais.</p><p class="mt-4">Foi preso, torturado e condenado à morte. No dia 4 de fevereiro de 1693, aos 46 anos, foi decapitado em Oriyur. Suas últimas palavras foram: "Morro com alegria pela fé de Cristo". Foi canonizado em 1947 pelo Papa Pio XII. É padroeiro das missões na Índia e modelo de diálogo inter-religioso e inculturação.</p><p class="mt-4"><b>Oração:</b> São João de Brito, apóstolo corajoso que deixastes pátria e nobreza para levar Cristo aos povos da Índia, ensinai-nos a respeitar todas as culturas enquanto proclamamos o Evangelho. Dai-nos coragem para testemunhar nossa fé mesmo diante das perseguições. Intercedei pelos missionários e por todos que trabalham pelo diálogo entre as religiões. Amém.</p><p class="mt-2 italic">São João de Brito, rogai por nós.</p>', isMartyr: true }] },
    { day: 5, month: 'Fevereiro', saints: [{ name: 'Santa Águeda', imageUrl: '/images/santa_agueda.png', story: '<h4>Virgem e Mártir</h4><p>Santa Águeda (ou Ágata) foi uma jovem cristã de nobre família siciliana que viveu no século III, durante a perseguição do imperador Décio. Consagrada a Deus desde a infância, fez voto de virgindade perpétua.</p><p class="mt-4">O cônsul Quintiniano, atraído por sua beleza e riqueza, tentou forçá-la a renunciar à fé cristã e casar-se com ele. Diante de sua firme recusa, mandou torturá-la cruelmente. Entre os tormentos, teve os seios arrancados. São Pedro apareceu-lhe na prisão e curou suas feridas. Porém, novos suplícios a levaram ao martírio por volta do ano 251.</p><p class="mt-4">Santa Águeda é invocada contra incêndios, terremotos e doenças do peito. É padroeira de Catânia, na Sicília, onde uma erupção do vulcão Etna foi milagrosamente detida pela intercessão da santa. Seu nome significa "boa" ou "bondosa" em grego.</p><p class="mt-4"><b>Oração:</b> Santa Águeda, virgem e mártir, que preferistes a morte à perda da pureza, intercedei por nós para que sejamos fiéis a Cristo em todas as circunstâncias. Protegei-nos dos perigos e alcançai-nos a graça da perseverança. Amém.</p><p class="mt-2 italic">Santa Águeda, rogai por nós.</p>', isMartyr: true }] },

    // MARÇO
    { day: 1, month: 'Março', saints: [{ name: 'São David', imageUrl: 'https://i.pinimg.com/736x/03/d2/c6/03d2c6fff3def641715392fab352e52a.jpg', story: '<h4>Padroeiro do País de Gales - Bispo e Confessor</h4><p>São David (Dewi Sant, em galês) nasceu por volta do ano 520 no País de Gales, filho do rei Sant de Ceredigion e de Santa Não. Desde o ventre materno, foi consagrado a Deus: uma tradição conta que, quando sua mãe foi ameaçada por um rei local, a terra se abriu e ela encontrou refúgio numa pedra, onde nasceu David, enquanto uma fonte milagrosa brotou do chão para seu batismo.</p><p class="mt-4">Educado por São Elfísio e depois pelo famoso monge São Paulino, David tornou-se sacerdote e depois fundou uma série de mosteiros no País de Gales e na Bretanha. Sua sede episcopal ficou em Mynyw (atual St Davids), cidade que recebe seu nome até hoje. Ali fundou um mosteiro marcado por extrema austeridade: seus monges trabalhavam nos campos sem o auxílio de animais, alimentavam-se apenas de pão, legumes e água — por isso David ficou conhecido como "o Aquático" (Aquaticus).</p><p class="mt-4">São David presidiu dois importantes sínodos: o de Brefi (c. 545), onde combateu a heresia pelagiana, e o de Caerleon (c. 560), que consolidou a organização da Igreja celta. Sua pregação era tão poderosa e sua presença tão marcante que, segundo a tradição, o chão se elevou sob seus pés enquanto pregava no Sínodo de Brefi, para que todos pudessem ouvi-lo — e uma pomba branca pousou em seu ombro, sinal do Espírito Santo.</p><p class="mt-4">Seus últimos dias foram marcados pela paz e pela santidade. Pouco antes de morrer, reuniu seus monges e discípulos e lhes deu sua última exortação, que se tornou famosa: <em>"Sede alegres, mantende vossa fé e realizai as pequenas coisas que ouvistes e vistes eu fazer."</em> Faleceu no dia 1° de março de 589 (ou 601, conforme algumas fontes), cercado por seus discípulos. Anjos e santos foram vistos rodeando sua cama de morte.</p><p class="mt-4">São David foi canonizado pelo Papa Calisto II em 1120 e declarado padroeiro do País de Gales. Dois peregrinos a St Davids equivaliam, segundo o Papa, a uma peregrinação a Roma. Seu dia é celebrado com orgulho enorme pelos galeses, que usam narcisos e alhos-porós em sua honra.</p><p class="mt-4"><b>Oração:</b> Ó São David, padroeiro do País de Gales, que vivestes em profunda austeridade e fervor apostólico, intercedei por nós. Que o vosso exemplo nos inspire a fazer fielmente as pequenas coisas da vida cristã com amor e dedicação. Rogai por toda a Igreja e por todos os que buscam a Deus com coração sincero. Amém.</p><p class="mt-2 italic">São David, rogai por nós.</p>' }] },
    { day: 2, month: 'Março', saints: [{ name: 'Santa Inês de Praga', imageUrl: 'https://i.pinimg.com/736x/a0/36/17/a0361768794440b0b893fff305db2ee3.jpg', story: '<h4>Princesa, Clarissa e Padroeira da Boêmia</h4><p>Santa Inês nasceu em 1211 em Praga, filha do rei Otacar I da Boêmia. Desde jovem foi prometida em casamento por razões políticas — primeiro ao filho do duque da Silésia, depois ao rei Henrique VII da Alemanha e até mesmo ao imperador Frederico II. Mas Inês recusou todos os pretendentes, pois havia decidido consagrar-se a Deus. Sua ousadia era extraordinária: ela escreveu ao Papa Gregório IX pedindo que intercedesse junto ao imperador para liberá-la do compromisso. O Papa atendeu, e Frederico II aceitou de bom grado, declarando: <em>"Se ela me houvesse desprezado por um mortal, eu me teria vingado; mas não posso ofender-me porque ela prefere o Rei do céu a mim."</em></p><p class="mt-4">Em 1234, com apenas 23 anos, fundou em Praga o primeiro convento de Clarissas a leste da Itália e a ele ingressou, renunciando a toda riqueza e privilégio real. Iniciou uma correspondência espiritual profunda com Santa Clara de Assis, que durou até a morte de Clara em 1253 — quatro cartas preciosas que chegaram até nós. Clara via em Inês uma filha, irmã e esposa de Cristo, e a exortava a perseverar na pobreza e na alegria.</p><p class="mt-4">No convento, Inês viveu com total desprendimento: cuidava dos doentes, lavava os pés dos leprosos e praticava as obras de misericórdia mais humildes. Fundou também um hospital e uma casa de acolhida para os pobres de Praga. Apesar de pertencer à família real, recusou-se a exercer qualquer posição de destaque, preferindo sempre o último lugar.</p><p class="mt-4">Inês faleceu em 2 de março de 1282, após quase 50 anos de vida claustral. Por séculos, o povo boêmio a venerou como santa, e sua intercessão foi invocada nos momentos mais dramáticos da história da nação. Foi beatificada pelo Papa Pio IX em 1874 e canonizada pelo Papa João Paulo II em 12 de novembro de 1989 — significativamente, apenas dias antes da Revolução de Veludo, que trouxe a liberdade à Tchecoslováquia. Muitos viram no acontecimento um sinal da intercessão de Inês pela sua nação.</p><p class="mt-4"><b>Oração:</b> Ó Santa Inês de Praga, princesa que renunciaste ao poder e à glória do mundo para seguir Cristo na pobreza e na humildade, intercedei por nós. Ensinai-nos a valorizar as riquezas do céu acima das riquezas da terra. Rogai por todos os que sofrem e pelos povos que buscam a liberdade e a paz. Amém.</p><p class="mt-2 italic">Santa Inês de Praga, rogai por nós.</p>' }] },
    { day: 3, month: 'Março', saints: [{ name: 'Santa Cunegunda', imageUrl: 'https://iili.io/qBc0KRR.png', story: '<h4>Imperatriz, Clarissa e Padroeira da Polônia</h4><p>Santa Cunegunda (Kinga) nasceu em 1224, filha do rei André II da Hungria e sobrinha-neta de Santa Isabel da Hungria. Desde jovem fez voto de virgindade, e quando foi prometida em casamento ao duque Bolesław V da Polônia — conhecido como "o Casto" — ele concordou em respeitar seu voto. Os dois viveram juntos por 40 anos como irmãos em castidade, dedicando suas vidas ao serviço do povo e de Deus.</p><p class="mt-4">Uma das lendas mais amadas sobre Santa Kinga conta que, ao partir da Hungria para a Polônia, ela lançou seu anel de noivado numa mina de sal na Hungria. Ao chegar à Polônia, pediu que cavassem o solo em Wieliczka — e lá encontraram uma enorme mina de sal, com o anel dela no primeiro bloco extraído. Esse presente fez dela a padroeira dos mineiros de sal e trouxe enorme prosperidade à Polônia. A magnífica mina de sal de Wieliczka, Patrimônio da Humanidade pela UNESCO, é considerada seu presente ao povo polonês.</p><p class="mt-4">Cunegunda governou com grande sabedoria e caridade: construiu igrejas, hospitais e conventos; defendeu o povo dos ataques tártaros; distribuiu seus bens aos pobres. Após a morte do marido em 1279, ingressou no convento das Clarissas em Stary Sącz, que ela mesma havia fundado, onde viveu os últimos anos de sua vida em profunda oração, pobreza e penitência, chegando a exercer os serviços mais humildes do convento.</p><p class="mt-4">Faleceu em 24 de julho de 1292, com fama de santidade. Seu corpo foi encontrado incorrupto. Foi beatificada em 1690 pelo Papa Alexandre VIII e canonizada em 16 de junho de 1999 pelo Papa João Paulo II, durante sua visita à Polônia. É padroeira da Polônia, Hungria, Lituânia e dos mineiros de sal.</p><p class="mt-4"><b>Oração:</b> Ó Santa Cunegunda, rainha que renunciaste às pompas do mundo para servir a Cristo e aos pobres, intercedei por nós. Ensinai-nos a usar os bens que recebemos não para nossa glória, mas para a glória de Deus e o bem dos irmãos. Protegei a Polônia, a Hungria e todos os que vos invocam. Amém.</p><p class="mt-2 italic">Santa Cunegunda, rogai por nós.</p>' }] },
    { day: 4, month: 'Março', saints: [{ name: 'São Casimiro', imageUrl: 'https://i.pinimg.com/736x/91/a4/cc/91a4cc5ab62e0983b5f354be7f703307.jpg', story: '<h4>Príncipe da Polônia - Modelo de Pureza e Devoção</h4><p>São Casimiro nasceu em 3 de outubro de 1458, no Castelo de Wawel, em Cracóvia, Polônia. Era o terceiro filho do rei Casimiro IV da Polônia e da rainha Isabel da Áustria. Desde a infância, destacou-se por sua profunda piedade, pureza de vida e amor aos pobres, virtudes que o tornaram um dos santos mais amados da Europa Oriental.</p><p class="mt-4">Educado por grandes mestres, incluindo o célebre humanista João Długosz, Casimiro recebeu formação tanto nas ciências quanto na fé cristã. Apesar de sua posição privilegiada como príncipe, escolheu viver com simplicidade e austeridade. Dormia no chão, jejuava frequentemente e passava longas horas em oração diante do Santíssimo Sacramento.</p><p class="mt-4">Tinha especial devoção à Virgem Maria e à Paixão de Cristo. Seu hino mariano favorito era "Omni die dic Mariae" (Diariamente diz a Maria), que recitava com fervor. Pediu que este hino fosse enterrado com ele. Quando seu túmulo foi aberto 120 anos depois, o pergaminho com o hino foi encontrado intacto sobre seu peito.</p><p class="mt-4">Aos 13 anos, foi pressionado por nobres húngaros a liderar uma campanha militar para conquistar o trono da Hungria. Relutante, obedeceu ao pai, mas quando percebeu que a guerra seria injusta, recusou-se a prosseguir e voltou para casa, preferindo desagradar ao pai a ofender a Deus. Seu pai tentou casá-lo com uma princesa, mas Casimiro havia feito voto de castidade perpétua e recusou firmemente, tornando-se modelo de pureza para os jovens.</p><p class="mt-4">Contraiu tuberculose ainda jovem e faleceu em 4 de março de 1484, aos 25 anos, em Grodno, enquanto visitava a Lituânia. Foi canonizado em 1521 pelo Papa Leão X. É padroeiro da Polônia, Lituânia e da juventude.</p><p class="mt-4"><b>Oração:</b> São Casimiro, príncipe puro e humilde, que preferistes a santidade às honras do mundo, ensinai-nos a buscar primeiro o Reino de Deus. Intercedei pelos jovens para que vivam em castidade e pureza. Amém.</p><p class="mt-2 italic">São Casimiro, rogai por nós.</p>' }] },
    { day: 5, month: 'Março', saints: [{ name: 'São João José da Cruz', imageUrl: 'https://iili.io/qBlIFF2.png', imageObjectPosition: 'center 30%', story: '<h4>Príncipe da Penitência - Franciscano Alcantarino</h4><p>São João José da Cruz nasceu em 15 de agosto de 1654, na ilha de Ischia, no Reino de Nápoles, Itália. De família nobre, desde jovem sentiu o chamado à vida religiosa e à penitência. Aos 16 anos, ingressou na Ordem dos Frades Menores Alcantarinos — a reforma mais austera do franciscanismo, fundada por São Pedro de Alcântara — e tornou-se um dos maiores místicos da Itália do século XVII.</p><p class="mt-4">Sua vida foi marcada por mortificações extremas: dormia apenas três horas por noite sobre uma prancha de madeira, jejuava rigorosamente durante longos períodos, andava descalço mesmo no inverno e usava uma rude cilícia. Ao mesmo tempo, sua presença irradiava uma paz e uma alegria sobrenatural que atraía multidões. Era chamado de "Príncipe da Penitência" pela intensidade de suas práticas ascéticas.</p><p class="mt-4">Dotado de dons místicos extraordinários, João José levitava durante a oração, bilocalzava-se (aparecia em dois lugares ao mesmo tempo), curava enfermos pelo simples toque das mãos e tinha o dom da leitura dos corações. Muitos pecadores convertiam-se apenas ao estar em sua presença. Era especialmente amado pelos pobres, aos quais servia com caridade sem limite.</p><p class="mt-4">Exerceu vários cargos na Ordem: guardião, vigário provincial e fundador de novos conventos. Porém, fugia das honras e preferia os últimos serviços. Apesar de ser italiano, sempre falava em espanhol por amor à espiritualidade alcantarina de origem espanhola — gesto que seus irmãos achavam curioso e tocante.</p><p class="mt-4">Faleceu em 5 de março de 1734, em Nápoles, aos 79 anos, com fama de santidade. Foi beatificado em 1789 pelo Papa Pio VI e canonizado em 26 de maio de 1839 pelo Papa Gregório XVI.</p><p class="mt-4"><b>Oração:</b> Ó São João José da Cruz, que fundaste tua vida sobre a penitência, a oração e o amor aos pobres, intercedei por nós. Ensinai-nos a vencer nossas paixões e a buscar a Deus com coração purificado. Amém.</p><p class="mt-2 italic">São João José da Cruz, rogai por nós.</p>' }] },
    { day: 6, month: 'Março', saints: [{ name: 'Santa Rosa de Viterbo', imageUrl: 'https://i.pinimg.com/736x/e1/29/6f/e1296fceeed390295cd1267b115845c9.jpg', story: '<h4>Virgem e Terceira de São Francisco</h4><p>Santa Rosa nasceu por volta de 1235 em Viterbo, cidade do Lácio, no centro da Itália. Desde criança foi marcada por intensas experiências espirituais. Aos 8 anos, conta a tradião que caiu gravemente enferma e chegou aos limiares da morte; diante das orações da família, recuperou-se de modo repentino, atribuindo sua cura a São Francisco de Assis, que lhe teria aparecido durante a enfermidade. A partir de então, passou a nutrir profunda devoção ao Poverello de Assis.</p><p class="mt-4">Com apenas 12 anos, Rosa quis ingressar no mosteiro das Clarissas de Viterbo, mas foi recusada por ser considerada muito fragil. Não desanimou: tornou-se terciária franciscana e começou a pregar pelas ruas de Viterbo, descalça e usando o hábito franciscano. Sua pregação, apaixonada e ardente, atraía multidões — não apenas pela palavra, mas pelos prodígios que a acompanhavam. Curou doentes, converteu pecadores e inflamava os corações de amor por Deus e pela Igreja.</p><p class="mt-4">O contexto político era turbulento: o imperador Frederico II estava em guerra com o Papado e Viterbo estava do lado imperial. Rosa ousou pregar publicamente em favor do Papa e contra o imperador, o que lhe valeu o exílio em 1250. Junto com sua família, foi expulsa da cidade. Ela aceitou o exílio com paz, declarando: <em>"Não sofro pelo Evangelho: é Cristo que sofre em mim."</em></p><p class="mt-4">Com a morte de Frederico II em 1250, Rosa pôde retornar a Viterbo em triunfo. Tentou novamente entrar para o convento das Clarissas, mas foi recusada de novo — e profetizou que elas a receberiam depois da sua morte. Faleceu em 6 de março de 1252, com apenas 17 anos, deixando fama de extraordinária santidade. Seu corpo permaneceu incorrupto. Três anos depois, o Papa Alexandre IV mandou transladar seus restos para o mosteiro das Clarissas de Viterbo — exatamente como Rosa havia predito.</p><p class="mt-4">Foi canonizada em 1457 pelo Papa Calisto III. É padroeira de Viterbo e invocada pelas jovens e pelos que pregam a fé.</p><p class="mt-4"><b>Oração:</b> Ó Santa Rosa de Viterbo, virgem ardente que pregastes o Evangelho sem temer oposições, intercedei por nós. Ensinai-nos a amar a Igreja e a defender a fé com coragem e humildade. Amém.</p><p class="mt-2 italic">Santa Rosa de Viterbo, rogai por nós.</p>' }] },
    { day: 7, month: 'Março', saints: [{ name: 'Santas Perpétua e Felicidade', imageUrl: 'https://misericordia.com.br/wp-content/uploads/2022/03/ALIANCA-MODELO-POST-2.jpg', story: '<h4>Mártires de Cartago - Unidas pela Fé e pelo Martírio</h4><p>Santas Perpétua e Felicidade são duas das mártires mais amadas da história da Igreja, e seu martírio em Cartago no ano de 203 d.C. permanece até hoje como um dos testemunhos mais belos de fé heroica nos primórdios do Cristianismo.</p><p class="mt-4">Santa Perpétua era uma jovem nobre de Cartago, no Norte da África, com cerca de 22 anos, casada e mãe de um filho recém-nascido. Felicidade, por sua vez, era escrava da família de Perpétua e estava grávida quando foram presas. Ambas eram cristãs e se recusaram a apostatar — a renunciar à sua fé para salvar a vida — mesmo sob imensa pressão do pai de Perpétua, que a implorou em lágrimas que abándonasse a fé por amor a ele e ao filho recém-nascido.</p><p class="mt-4">Enquanto estava presa, Perpétua escreveu um diário péssimo que chegou até nós — um dos raros documentos escritos por uma mulher na Antiguidade. Nele narra com lucidez e serenidade os interrogatórios, as visões que recebeu de Deus, a saudade do filho e a paz interior que a sustentava. Felicidade, por sua vez, temia ser executada depois das demais por causa da gestação — as leis romanas proibiam executar gesta portes. Rezou para que seu filho nascesse antes. Deus a atendeu: o bebê nasceu dois dias antes do martírio e foi adotado por uma irmã da comunidade cristã.</p><p class="mt-4">No dia 7 de março de 203, na arena romana de Cartago, Perpétua e Felicidade foram jogadas a animais selvagens e, finalmente, degoladas. Os relatos da época descrevem como as duas se mantiveram serenas e até alegres ao enfrentar a morte, encorajando os outros mártires. Antes de morrer, Perpétua guiou a espada do verdugo, pois ele havia errado o golpe — tal era sua força interior.</p><p class="mt-4">O Papa São João Paulo II escreveu sobre Perpétua e Felicidade: <em>"Duas mulheres cristãs não tiveram medo da morte — e seu testemunho continua a falar ao coração dos homens dois mil anos depois."</em></p><p class="mt-4"><b>Oração:</b> Santas Perpétua e Felicidade, mártires heroicas que preferistes a morte à renúncia à fé, intercedei por nós. Dai-nos a coragem de sermos fiéis a Cristo em todos os momentos de nossa vida, mesmo quando a fé nos custa caro. Amém.</p><p class="mt-2 italic">Santas Perpétua e Felicidade, rogai por nós.</p>', isMartyr: true }] },
    { day: 8, month: 'Março', saints: [{ name: 'São João de Deus', imageUrl: '/images/sao_joao_de_deus.png', story: '<h4>São João de Deus - Herói da Caridade</h4><p>João Cidade nasceu em Portugal em 1495. Levou uma vida errante como soldado e pastor, longe de Deus. Aos 40 anos, ouviu um sermão de São João de Ávila que o abalou profundamente. Tomado de arrependimento, começou a agir de forma tão exaltada que foi internado num hospício. Mas foi justamente naquele lugar de sofrimento que Deus lhe revelou sua missão: cuidar dos doentes e dos pobres.</p><p class="mt-4">Após sua conversão, fundou em Granada o primeiro hospital onde os doentes eram tratados com dignidade e amor. Ele mesmo carregava os enfermos nas costas pelas ruas da cidade, lavava suas feridas, consolava os moribundos. Via em cada doente o rosto sofredor de Cristo. Seu lema era: "Fazei o bem a vós mesmos, irmãos, fazendo-o aos outros."</p><p class="mt-4">João não fazia distinção entre os doentes: ricos e pobres, cristãos e mouros, virtuosos e pecadores — todos recebiam o mesmo cuidado amoroso. Confiava totalmente na Providência divina para sustentar seu hospital. Apesar de toda a sua obra extraordinária, se considerava o maior dos pecadores, nunca aceitando honras ou reconhecimentos.</p><p class="mt-4">Morreu em 8 de março de 1550, aos 55 anos, esgotado pelo trabalho e pela caridade, ajoelhado diante do Crucifixo. Foi canonizado em 1690 e declarado padroeiro dos doentes e dos hospitais pelo Papa Leão XIII em 1886. Seus discípulos fundaram a Ordem dos Irmãos Hospitaleiros de São João de Deus, que hoje mantém centenas de hospitais em todo o mundo.</p><p class="mt-4"><b>Oração:</b> Ó São João de Deus, que viste o rosto de Cristo em cada doente e pobre, intercede por todos os enfermos e pelos profissionais de saúde. Alcança-nos a graça da cura física e espiritual. Amém.</p><p class="mt-2 italic">São João de Deus, rogai por nós.</p>' }] },
    { day: 9, month: 'Março', saints: [{ name: 'Santa Francisca Romana', imageUrl: 'https://www.oarcanjo.net/site/wp-content/uploads/Santa-Francisca-Romana-584x1024.jpg', story: '<h4>Esposa, Mãe, Viúva e Fundadora</h4><p>Santa Francisca Romana nasceu em Roma, em 1384, numa família nobre e piedosa. Desde criança sentia o chamado à vida religiosa, mas obedeceu ao desejo de seus pais e, aos 13 anos, casou-se com Lorenzo dei Ponziani, um nobre romano. O casamento, inicialmente contrário ao seu desejo, tornou-se um campo de santidade: Francisca foi esposa fidelíssima, mãe dedicada de três filhos e administradora sábia de um lar cristão.</p><p class="mt-4">Durante décadas suportou com heroica paciência guerras, pestes, mortes de filhos e as tribulações trazidas pelas guerras civis de Roma. Quando sua cidade foi assolada pela terrível epidemia de 1410, ela converteu parte de seu palácio em hospital, servindo pessoalmente os doentes. Perdeu dois filhos na infância e enfrentou o exílio forçado de seu marido com total resignação à vontade de Deus.</p><p class="mt-4">Francisca era privilegiada com visões místicas extraordinárias. Segundo a tradição, via continuamente seu anjo da guarda — descrito como um menino resplandecente — que a iluminava e protegia. Recebeu também visões de Nossa Senhora, de Cristo crucificado e dos santos. Sua vida de oração era intensa, passando longas horas em contemplação, muitas vezes em êxtase.</p><p class="mt-4">Após a morte do marido em 1436, Francisca ingressou na comunidade que ela mesma havia fundado anos antes: as Oblatas de Maria, depois chamadas Oblatas de Santa Francisca Romana, um grupo de mulheres nobres que viviam segundo a Regra Beneditina sem clausura, dedicando-se à oração e às obras de caridade. Ali viveu os últimos quatro anos de sua vida em profunda paz e santidade, sendo reverenciada por todos como mãe espiritual.</p><p class="mt-4">Faleceu em 9 de março de 1440, com 56 anos, após uma breve doença. Seu último ato foi olhar para o seu anjo da guarda e dizer: "O anjo terminou sua missão. Ele me chama." Foi canonizada em 1608 pelo Papa Paulo V. É padroeira das motoristas e de Roma, e invocada pelas famílias cristãs.</p><p class="mt-4"><b>Oração:</b> Santa Francisca Romana, modelo de esposa, mãe e mulher consagrada, que encontrastes a santidade nas obrigações do lar e no serviço aos pobres, intercedei por nossas famílias. Ensinai-nos a cumprir nossos deveres cotidianos com amor a Deus e ajudai-nos a ver, como vós víeis, a presença dos anjos que nos guardam. Amém.</p><p class="mt-2 italic">Santa Francisca Romana, rogai por nós.</p>' }] },
    { day: 10, month: 'Março', saints: [{ name: 'Santa Maria Eugênia de Jesus', imageUrl: 'https://religiosasdaassuncao.org.br/wp-content/uploads/2021/02/maria-eugenia-fundadora-min-623x1024.jpg', story: '<h4>Virgem e Fundadora das Religiosas da Assunção</h4><p>Santa Maria Eugênia Milleret de Brou nasceu em 25 de agosto de 1817 em Metz, França, numa família burguesa e sofisticada, mas pouco religiosa. Sua infância foi marcada pela instabilidade: os pais se separaram, e ela passou por vários colégios. Apesar de receber uma educação refinada, cresceu praticamente sem fé.</p><p class="mt-4">Sua conversão se deu de forma gradual mas poderosa. Aos 18 anos, tocada pela pregação do Padre Henri Lacordaire durante o Advento de 1836 em Notre-Dame de Paris, Maria Eugênia redescobriu a fé com ardor. Aquelas conferências iluminaram sua mente e transformaram seu coração. Nelas, ela não apenas encontrou Deus — encontrou também o sentido de toda a sua vida.</p><p class="mt-4">Em 1839, com apenas 22 anos, fundou em Paris a Congregação das Religiosas da Assunção, uma nova família religiosa voltada à educação cristã das mulheres. Sua intuição era clara: para transformar a sociedade, era preciso formar mulheres com profundidade espiritual, inteligência e coração cristão. Reuniu ao seu redor jovens animadas pelo mesmo ideal e estabeleceu as bases de uma obra que se espalharia pelo mundo inteiro.</p><p class="mt-4">Sua espiritualidade tinha como centro o mistério da Assunção de Maria — o triunfo do amor de Deus sobre a morte — e se caracterizava pela alegria, pela inteligência a serviço da fé e pelo amor concreto aos pobres. Governou a congregação por mais de 50 anos com sabedoria e humildade, enfrentando dificuldades financeiras, incompreensões e a difícil aplicação das leis anticlericais francesas do final do século XIX.</p><p class="mt-4">Faleceu em 10 de março de 1898, em Paris, deixando uma congregação sólida, com mais de 400 religiosas espalhadas por toda a Europa. Foi beatificada pelo Papa Paulo VI em 1975 e canonizada pelo Papa João Paulo II em 3 de junho de 2007. Suas Religiosas da Assunção hoje atuam em mais de 40 países, fiéis ao seu sonho de educar mulheres para transformar o mundo em Cristo.</p><p class="mt-4"><b>Oração:</b> Santa Maria Eugênia de Jesus, que encontrastes em Cristo a resposta a todas as buscas do coração humano e dedicastes a vida à educação das mulheres pela fé, intercedei por nós. Ensinai-nos a usar nossa inteligência e nossos talentos a serviço de Deus e do próximo. Amém.</p><p class="mt-2 italic">Santa Maria Eugênia de Jesus, rogai por nós.</p>' }] },
    { day: 11, month: 'Março', saints: [{ name: 'São Constantino', imageUrl: 'https://diocesedebraganca.com.br/imagens/upload/d8cbdfde2e7c7351f25bdcf2a9623ea883ec62da.jpg', story: '<h4>Rei, Monge e Mártir da Escócia</h4><p>São Constantino nasceu por volta do ano 863, filho do rei Áed da Escócia. Tornou-se rei dos escoceses (Dál Riata e Pictland) por volta de 877 e governou com coragem num dos períodos mais sangrentos da história do seu povo, marcado pelas constantes invasões dos Vikings nórdicos que devastavam os mosteiros e aldeias da Escócia e da Irlanda.</p><p class="mt-4">Após décadas de reinado, Constantino tomou uma decisão que surpreendeu a todos: abdicou do trono e retirou-se para a vida religiosa. Ingressou no mosteiro de St Andrews, em Fife, onde viveu como monge simples, entregando-se à oração, à penitência e ao serviço dos irmãos. Depois de algum tempo como monge, tornou-se prior do mosteiro — liderando a comunidade pela santidade de vida mais do que pela antiga autoridade real.</p><p class="mt-4">Segundo a tradição, após a vida monástica, Constantino saiu para pregar a fé aos pagãos e foi martirizado pelos povos nórdicos ou pelos pictos pagãos. Foi venerado como mártir e confessou a fé até o fim.</p><p class="mt-4">Sua vida é um testemunho extraordinário de como a grandeza mundana nada vale diante do chamado de Deus. Um rei que abandona o poder para servir como monge e depois dá a vida pela fé é ícone da conversão total ao Evangelho.</p><p class="mt-4"><b>Oração:</b> São Constantino, rei que renunciaste à coroa para servir a Cristo no silêncio do mosteiro, intercedei por nós. Ensinai-nos que a verdadeira grandeza está no serviço e na humildade, e que toda riqueza do mundo não vale a paz de uma alma entregue a Deus. Amém.</p><p class="mt-2 italic">São Constantino, rogai por nós.</p>' }] },
    { day: 12, month: 'Março', saints: [{ name: 'São Luís Orione', imageUrl: 'https://i.pinimg.com/736x/3e/84/a4/3e84a40dc38b2a4f6ed4ad7a6bb1c8ee.jpg', story: '<h4>São Luís Orione - Fundador da Pequena Obra da Divina Providência</h4><p>São Luís Orione nasceu em 23 de junho de 1872 em Pontecurone, na Itália. Desde jovem sentiu o chamado ao serviço dos mais pobres e abandonados. Foi aluno de São João Bosco em Turim. Em 1893, fundou a Pequena Obra da Divina Providência, voltada ao atendimento dos mais necessitados. Seu lema era: "Fazer o bem a todos, mal a ninguém." Faleceu em 12 de março de 1940, com as palavras "Jesus, Jesus, Jesus" nos lábios. Canonizado em 2004 pelo Papa João Paulo II.</p><p class="mt-4"><b>Oração:</b> São Luís Orione, que vistes o rosto de Cristo nos mais pobres, ensinai-nos a servir com alegria. Amém.</p><p class="mt-2 italic">São Luís Orione, rogai por nós.</p>' }] },
    { day: 13, month: 'Março', saints: [{ name: 'São Rodrigo e Salomão', imageUrl: 'https://i.pinimg.com/1200x/6f/f1/23/6ff1237b0a4574cafceb84368506878d.jpg', story: '<h4>Mártires de Córdoba - Fiéis até a Morte</h4><p>São Rodrigo e Salomão foram dois mártires cristãos que sofreram o martírio em Córdoba, Espanha, no século IX, durante o período da dominação moura. Rodrigo era um sacerdote cristão de vida exemplar. Teve dois irmãos: um cristão fiel e outro que havia apostatado e convertido ao islamismo.</p><p class="mt-4">Após uma briga entre os irmãos, o irmão apóstata acusou Rodrigo falsamente de ter renunciado ao Islã. Rodrigo foi preso e encarcerado. Na prisão, conheceu Salomão, outro cristão encarcelado pelo mesmo motivo. Os dois se fortaleceram mutuamente na fé, recusando-se a apostatar. Foram decapitados juntos em 13 de março de 857. Seu martírio foi narrado por São Eulogio de Córdoba.</p><p class="mt-4"><b>Oração:</b> São Rodrigo e Salomão, mártires corajosos que preferistes a morte à negação de Cristo, intercedei por nós. Amém.</p><p class="mt-2 italic">São Rodrigo e Salomão, rogai por nós.</p>', isMartyr: true }] },
    { day: 14, month: 'Março', saints: [{ name: 'Santa Matilde', imageUrl: 'https://i.pinimg.com/736x/66/59/7d/66597d4cc06a66cdab0ae3ebb0e83d0d.jpg', story: '<h4>Santa Matilde - Rainha da Germânia</h4><p>Santa Matilde nasceu por volta de 892, na Westfália. Era filha do conde Dietrich e de Reinilda. Educada por sua avó, a abadessa de Herford, cresceu em um ambiente de profunda piedade. Casou-se com Henrique, duque da Saxônia, que mais tarde se tornou o rei Henrique I da Germânia.</p><p class="mt-4">Como rainha, Matilde foi um modelo de humildade e caridade. Enquanto seu marido se ocupava das guerras e da política, ela se dedicava a aliviar o sofrimento dos súditos, visitando doentes e socorrendo os pobres. Ela via no serviço aos humildes um serviço ao próprio Cristo.</p><p class="mt-4">Após a morte de Henrique em 936, Matilde enfrentou grandes provações, inclusive a ingratidão de seus filhos, Otto I e Henrique, que a acusaram de dissipar o tesouro real com suas esmolas excessivas. Ela suportou tudo com paciência heroica, chegando a retirar-se para um mosteiro para não ser causa de discórdia. Mais tarde, reconciliou-se com eles.</p><p class="mt-4">Fundou vários mosteiros, entre eles os de Quedlinburg, Nordhausen e Enger. Passou seus últimos anos em Quedlinburg, dedicada à oração e à penitência. Faleceu em 14 de março de 968. É padroeira das famílias numerosas e das viúvas.</p><p class="mt-4"><b>Oração:</b> Senhor, que concedestes à Rainha Santa Matilde a graça de Vos servir com humildade e caridade, dai-nos, por sua intercessão, a força para Vos amar sobre todas as coisas e servir-Vos em nossos irmãos necessitados. Amém.</p><p class="mt-2 italic">Santa Matilde, rogai por nós.</p>' }] },
    {
        day: 15, month: 'Março', saints: [
            { name: 'Domingo Laetare', imageUrl: 'https://i.pinimg.com/736x/f7/e3/76/f7e3763772dc14fb2e28cdc822bf7290.jpg', story: '<h4>Domingo Laetare - O Domingo da Alegria</h4><p>O Domingo Laetare é o quarto domingo da Quaresma, celebrado com alegria e esperança no meio do caminho penitencial. Seu nome vem das primeiras palavras do Introito da missa: <em>"Laetare Ierusalem!"</em> (Alegrai-vos, Jerusalém!), tiradas do profeta Isaías.</p><p class="mt-4">É um dia de alívio e consolo no rigor da Quaresma. A Igreja usa as vestes litúrgicas na cor rosa (ou rósea), em vez do roxo penitencial, como sinal de antecipação da alegria pascal. Flores podem adornar o altar, e o órgão pode tocar com maior solenidade — sinais de que a Páscoa se aproxima.</p><p class="mt-4">Neste domingo, a Igreja nos lembra que a penitência não é fim em si mesma, mas caminho para a alegria da Ressurreição. O cristão que caminha pela Quaresma com espírito de conversão genuína começa a sentir já na metade do percurso a antecipação da luz da Páscoa.</p><p class="mt-4"><b>Oração:</b> Senhor Jesus, que com vossa Ressurreição convertereis nossa tristeza em alegria, dai-nos perseverar com fidelidade no caminho da Quaresma para que possamos celebrar com coração renovado a festa da Páscoa. Amém.</p>' },
            { name: 'São Longuinho', imageUrl: 'https://i.pinimg.com/736x/fa/2d/7f/fa2d7f33e80fa5c8f7ee55476f273fe0.jpg', story: '<h4>São Longuinho - O Centurião da Cruz</h4><p>São Longuinho é o nome dado pela tradição cristã ao soldado romano que, segundo o Evangelho de São João (19,34), abriu o lado de Jesus crucificado com uma lança. Do lado traspassado brotou imediatamente sangue e água — símbolo dos sacramentos do Batismo e da Eucaristia que nascem da Paixão de Cristo.</p><p class="mt-4">Segundo a tradição, Longuinho sofria de uma doença nos olhos e, ao receber nas faces o sangue e a água que escorreram da lança, foi milagrosamente curado. Essa cura tocou seu coração e o levou à conversão imediata: ele confessou diante de todos que Jesus era verdadeiramente o Filho de Deus — tornando-se assim o primeiro a proclamar a divindade de Cristo após sua morte.</p><p class="mt-4">Após deixar o exército romano, Longuinho teria viajado para a Capadócia (atual Turquia), onde se tornou monge e pregador do Evangelho. Converteu muitos à fé cristã até ser preso pelo governador romano. Torturado e interrogado, recusou-se a adorar os ídolos pagãos, e foi decapitado por volta do ano 45 d.C.</p><p class="mt-4">A Santa Lança, relíquia ligada a Longuinho, é venerada na Basílica de São Pedro, no Vaticano. São Longuinho é padroeiro dos soldados e das pessoas que buscam a cura de doenças dos olhos.</p><p class="mt-4"><b>Oração:</b> Ó São Longuinho, que tocastes o Lado de Cristo e fostes por Ele curado e transformado, intercedei por nós. Que como vós, saibamos reconhecer em Jesus o Filho de Deus e testemunhar nossa fé com coragem. Amém.</p><p class="mt-2 italic">São Longuinho, rogai por nós.</p>', isMartyr: true }
        ]
    },
    { day: 17, month: 'Março', saints: [{ name: 'São Patrício', imageUrl: 'https://i.pinimg.com/736x/5e/6f/7a/5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b.jpg', story: '<h4>Apóstolo da Irlanda</h4><p>São Patrício evangelizou a Irlanda no século V. Usou o trevo de três folhas para explicar a Santíssima Trindade.</p><p class="mt-4"><b>Oração:</b> São Patrício, rogai por nós.</p>' }] },
    { day: 18, month: 'Março', saints: [{ name: 'São Cirilo de Jerusalém', imageUrl: 'https://i.pinimg.com/736x/6f/7a/8b/6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c.jpg', story: '<h4>Doutor da Igreja</h4><p>São Cirilo, bispo de Jerusalém e Doutor da Igreja, escreveu catequeses famosas sobre os sacramentos e a fé cristã.</p><p class="mt-4"><b>Oração:</b> São Cirilo de Jerusalém, rogai por nós.</p>' }] },
    { day: 19, month: 'Março', saints: [{ name: 'São José', imageUrl: 'https://iili.io/fj7jrtj.png', story: '<h4>Esposo de Maria</h4><p>São José, esposo da Virgem Maria e pai nutrício de Jesus. Padroeiro da Igreja Universal, dos trabalhadores e das famílias.</p><p class="mt-4"><b>Oração:</b> São José, rogai por nós.</p>' }] },
    { day: 25, month: 'Março', saints: [{ name: 'Anunciação do Senhor', imageUrl: 'https://i.pinimg.com/736x/7a/8b/9c/7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d.jpg', story: '<h4>Anunciação</h4><p>O Anjo Gabriel anuncia a Maria que ela será a Mãe de Deus. Maria responde: "Eis aqui a serva do Senhor."</p><p class="mt-4"><b>Oração:</b> Ave Maria, cheia de graça.</p>' }] },

    // ABRIL
    { day: 23, month: 'Abril', saints: [{ name: 'São Jorge', imageUrl: 'https://i.pinimg.com/736x/8b/9c/0d/8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e.jpg', story: '<h4>Mártir e Guerreiro</h4><p>São Jorge, soldado romano que morreu mártir pela fé cristã. Padroeiro de Portugal, Inglaterra e do escotismo.</p><p class="mt-4"><b>Oração:</b> São Jorge, rogai por nós.</p>', isMartyr: true }] },
    { day: 25, month: 'Abril', saints: [{ name: 'São Marcos Evangelista', imageUrl: 'https://i.pinimg.com/736x/9c/0d/1e/9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f.jpg', story: '<h4>Evangelista</h4><p>São Marcos, autor do segundo Evangelho. Companheiro de São Pedro e São Paulo nas missões.</p><p class="mt-4"><b>Oração:</b> São Marcos, rogai por nós.</p>' }] },
    { day: 29, month: 'Abril', saints: [{ name: 'Santa Catarina de Siena', imageUrl: 'https://i.pinimg.com/736x/0d/1e/2f/0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a.jpg', story: '<h4>Doutora da Igreja</h4><p>Santa Catarina de Siena, mística dominicana, Doutora da Igreja. Teve grande influência na Igreja do século XIV.</p><p class="mt-4"><b>Oração:</b> Santa Catarina de Siena, rogai por nós.</p>' }] },

    // MAIO
    {
        day: 1, month: 'Maio', saints: [
            { name: 'São José Operário', imageUrl: 'https://i.pinimg.com/736x/1e/2f/3a/1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b.jpg', story: '<h4>Trabalhador</h4><p>São José, modelo dos trabalhadores. Celebramos seu trabalho humilde como carpinteiro.</p><p class="mt-4"><b>Oração:</b> São José Operário, rogai por nós.</p>' },
            {
                name: 'Nossa Senhora do Líbano',
                imageUrl: '/images/ns_libano_1.png',
                story: '<h4>Rainha do Líbano</h4><p>Nossa Senhora do Líbano é a padroeira do Líbano e um dos títulos mais majestosos da Virgem Maria no Oriente Médio. Seu santuário em Harissa é um símbolo de unidade e paz entre as religiões.</p><p class="mt-4"><b>Oração:</b> Ó Maria, Rainha do Líbano, protegei nossas famílias e fazei de nós instrumentos de vossa paz. Amém.</p>'
            }
        ]
    },
    { day: 8, month: 'Maio', saints: [{ name: 'Nossa Senhora de Luján', imageUrl: '/images/ns_lujan.png', story: '<h4>Padroeira da Argentina</h4><p>Nossa Senhora de Luján é a padroeira da Argentina. Sua imagem escolheu milagrosamente permanecer em Luján em 1630, tornando-se o coração da fé argentina.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora de Luján, rogai por nós.</p>' }] },
    { day: 13, month: 'Maio', saints: [{ name: 'Nossa Senhora de Fátima', imageUrl: '/images/ns_fatima.png', story: '<h4>Aparições em Fátima</h4><p>Em 1917, Nossa Senhora apareceu a três pastorinhos em Fátima, Portugal, pedindo oração do Rosário.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora de Fátima, rogai por nós.</p>' }] },
    { day: 22, month: 'Maio', saints: [{ name: 'Santa Rita de Cássia', imageUrl: 'https://i.pinimg.com/736x/3a/4b/5c/3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d.jpg', story: '<h4>Santa das Causas Impossíveis</h4><p>Santa Rita, religiosa agostiniana, conhecida como advogada das causas impossíveis e desesperadas.</p><p class="mt-4"><b>Oração:</b> Santa Rita de Cássia, rogai por nós.</p>' }] },
    {
        day: 24, month: 'Maio', saints: [{
            name: 'Nossa Senhora de Sheshan',
            imageUrl: '/images/ns_sheshan_1.jpg',
            story: '<h4>Auxiliadora dos Cristãos</h4><p>Nossa Senhora de Sheshan é a padroeira da China. Sua estátua no topo da basílica mostra Maria elevando o Menino Jesus, apresentando-O como o único Salvador. É um símbolo de esperança para os cristãos na Ásia.</p><p class="mt-4"><b>Oração:</b> Ó Senhora de Sheshan, auxiliai os cristãos e trazei a paz à China. Amém.</p>'
        }]
    },
    {
        day: 31, month: 'Maio', saints: [{
            name: 'Nossa Senhora de Trà Kiệu',
            imageUrl: '/images/ns_tra_kieu_1.jpg',
            story: '<h4>Auxiliadora e Protetora</h4><p>Nossa Senhora de Trà Kiệu é a padroeira do Vietnã central. Em 1885, ela apareceu para proteger os católicos sitiados, desviando as balas e flechas dos atacantes, que a chamaram de "Senhora General".</p><p class="mt-4"><b>Oração:</b> Senhora de Trà Kiệu, protegei a Igreja e dai coragem aos vossos filhos. Amém.</p>'
        }]
    },

    // JUNHO
    { day: 13, month: 'Junho', saints: [{ name: 'Santo Antônio de Pádua', imageUrl: 'https://i.pinimg.com/736x/4b/5c/6d/4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e.jpg', story: '<h4>Doutor da Igreja</h4><p>Santo Antônio, franciscano português, grande pregador e Doutor da Igreja. Padroeiro de Portugal e dos pobres.</p><p class="mt-4"><b>Oração:</b> Santo Antônio, rogai por nós.</p>' }] },
    { day: 24, month: 'Junho', saints: [{ name: 'São João Batista', imageUrl: 'https://i.pinimg.com/736x/5c/6d/7e/5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f.jpg', story: '<h4>Precursor do Senhor</h4><p>São João Batista, precursor de Jesus, batizou-O no rio Jordão. Único santo cuja natividade é celebrada.</p><p class="mt-4"><b>Oração:</b> São João Batista, rogai por nós.</p>' }] },
    { day: 29, month: 'Junho', saints: [{ name: 'São Pedro e São Paulo', imageUrl: 'https://i.pinimg.com/736x/6d/7e/8f/6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a.jpg', story: '<h4>Colunas da Igreja</h4><p>São Pedro, primeiro Papa, e São Paulo, apóstolo dos gentios. Pilares da Igreja primitiva.</p><p class="mt-4"><b>Oração:</b> São Pedro e São Paulo, rogai por nós.</p>' }] },

    // JULHO
    { day: 9, month: 'Julho', saints: [{ name: 'Nossa Senhora de Itatí', imageUrl: '/images/ns_itati.png', story: '<h4>Rainha do Paraná</h4><p>Nossa Senhora de Itatí é uma das devoções mais antigas e amadas da Argentina, especialmente em Corrientes. O nome significa "pedra branca" em guarani.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora de Itatí, rogai por nós.</p>' }] },
    { day: 11, month: 'Julho', saints: [{ name: 'São Bento', imageUrl: 'https://i.pinimg.com/736x/7e/8f/9a/7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b.jpg', story: '<h4>Pai do Monaquismo Ocidental</h4><p>São Bento de Núrsia, fundador da Ordem Beneditina. Sua Regra influenciou toda a vida monástica do Ocidente.</p><p class="mt-4"><b>Oração:</b> São Bento, rogai por nós.</p>' }] },
    { day: 16, month: 'Julho', saints: [{ name: 'Nossa Senhora do Carmo', imageUrl: 'https://i.pinimg.com/736x/8f/9a/0b/8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c.jpg', story: '<h4>Rainha do Carmelo</h4><p>Nossa Senhora do Carmo, padroeira da Ordem Carmelita. Entregou o escapulário a São Simão Stock.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora do Carmo, rogai por nós.</p>' }] },
    { day: 22, month: 'Julho', saints: [{ name: 'Santa Maria Madalena', imageUrl: 'https://i.pinimg.com/736x/9a/0b/1c/9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d.jpg', story: '<h4>Apóstola dos Apóstolos</h4><p>Santa Maria Madalena, primeira testemunha da Ressurreição de Cristo. Modelo de conversão e amor.</p><p class="mt-4"><b>Oração:</b> Santa Maria Madalena, rogai por nós.</p>' }] },
    { day: 25, month: 'Julho', saints: [{ name: 'São Tiago Maior', imageUrl: 'https://i.pinimg.com/736x/0b/1c/2d/0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e.jpg', story: '<h4>Apóstolo</h4><p>São Tiago, filho de Zebedeu, apóstolo e mártir. Padroeiro da Espanha e dos peregrinos.</p><p class="mt-4"><b>Oração:</b> São Tiago, rogai por nós.</p>', isMartyr: true }] },
    { day: 26, month: 'Julho', saints: [{ name: 'Sant\'Ana e São Joaquim', imageUrl: 'https://i.pinimg.com/736x/1c/2d/3e/1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f.jpg', story: '<h4>Pais de Maria</h4><p>Sant\'Ana e São Joaquim, pais da Virgem Maria e avós de Jesus. Modelos de fé e família.</p><p class="mt-4"><b>Oração:</b> Sant\'Ana e São Joaquim, rogai por nós.</p>' }] },

    // AGOSTO
    { day: 5, month: 'Agosto', saints: [{ name: 'Nossa Senhora de Copacabana', imageUrl: '/images/ns_copacabana.png', story: '<h4>Rainha da Bolívia</h4><p>Nossa Senhora de Copacabana é a padroeira da Bolívia. Sua imagem milagrosa, esculpida por Yupanqui nas margens do Lago Titicaca, é o centro da fé andina.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora de Copacabana, rogai por nós.</p>' }] },
    { day: 6, month: 'Agosto', saints: [{ name: 'Transfiguração do Senhor', imageUrl: 'https://i.pinimg.com/736x/2d/3e/4f/2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a.jpg', story: '<h4>Glória de Cristo</h4><p>Jesus se transfigura no Monte Tabor, revelando sua glória divina a Pedro, Tiago e João.</p><p class="mt-4"><b>Oração:</b> Senhor Jesus, rogai por nós.</p>' }] },
    { day: 10, month: 'Agosto', saints: [{ name: 'São Lourenço', imageUrl: 'https://i.pinimg.com/736x/3e/4f/5a/3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b.jpg', story: '<h4>Diácono e Mártir</h4><p>São Lourenço, diácono de Roma, martirizado em grelha ardente. Padroeiro dos cozinheiros.</p><p class="mt-4"><b>Oração:</b> São Lourenço, rogai por nós.</p>', isMartyr: true }] },
    { day: 13, month: 'Agosto', saints: [{ name: 'Santa Dulce dos Pobres', imageUrl: 'https://i.pinimg.com/736x/placeholder.jpg', story: '<h4>Santa Dulce dos Pobres - Anjo Bom da Bahia</h4><p>Santa Dulce Lopes Pontes nasceu em 26 de maio de 1914, em Salvador, Bahia, Brasil. Foi canonizada pelo Papa Francisco em 13 de outubro de 2019, tornando-se a primeira santa brasileira nata. Era chamada de "Anjo Bom da Bahia" por sua caridade sem limites com os pobres e doentes. Construiu em Salvador o maior complexo filantrópico da América Latina — Obras Sociais Irmã Dulce (OSID). Sofreu de graves problemas respiratórios por mais de 50 anos, mas nunca deixou de servir. Faleceu em 13 de março de 1992. Seu memorial litúrgico é celebrado em 13 de agosto.</p><p class="mt-4"><b>Oração:</b> Santa Dulce dos Pobres, Anjo Bom da Bahia, intercedei por todos os que sofrem. Amém.</p><p class="mt-2 italic">Santa Dulce dos Pobres, rogai por nós.</p>' }] },
    { day: 15, month: 'Agosto', saints: [{ name: 'Assunção de Nossa Senhora', imageUrl: '/images/ns_assuncao.png', story: '<h4>Assunção ao Céu</h4><p>Maria é elevada ao Céu em corpo e alma. Dogma proclamado pelo Papa Pio XII em 1950.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora, rogai por nós.</p>' }] },

    // SETEMBRO
    { day: 8, month: 'Setembro', saints: [{ name: 'Natividade de Nossa Senhora', imageUrl: '/images/ns_natividade.png', story: '<h4>Nascimento de Maria</h4><p>Celebramos o nascimento da Virgem Maria, Mãe de Deus e nossa Mãe.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora, rogai por nós.</p>' }] },
    { day: 14, month: 'Setembro', saints: [{ name: 'Exaltação da Santa Cruz', imageUrl: 'https://i.pinimg.com/736x/6b/7c/8d/6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e.jpg', story: '<h4>Triunfo da Cruz</h4><p>Celebramos a Cruz de Cristo, instrumento de nossa salvação e vitória sobre o pecado.</p><p class="mt-4"><b>Oração:</b> Adoramos-Vos, ó Cristo, e Vos bendizemos.</p>' }] },
    { day: 15, month: 'Setembro', saints: [{ name: 'Nossa Senhora das Dores', imageUrl: '/images/ns_dores_setembro.png', story: '<h4>Mãe Dolorosa</h4><p>Veneramos as sete dores de Maria, especialmente ao pé da Cruz de seu Filho.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora das Dores, rogai por nós.</p>' }] },
    { day: 25, month: 'Setembro', saints: [{ name: 'Nossa Senhora do Rosário de San Nicolás', imageUrl: '/images/ns_rosario_san_nicolas.png', story: '<h4>Maria em San Nicolás</h4><p>Nossa Senhora do Rosário de San Nicolás apareceu na Argentina em 1983, pedindo a conversão e a oração do Rosário para a paz do mundo.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora de San Nicolás, rogai por nós.</p>' }] },
    { day: 29, month: 'Setembro', saints: [{ name: 'São Miguel, Gabriel e Rafael', imageUrl: 'https://i.pinimg.com/736x/8d/9e/0f/8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a.jpg', story: '<h4>Arcanjos</h4><p>São Miguel, guerreiro de Deus; São Gabriel, mensageiro; São Rafael, curador. Protetores celestes.</p><p class="mt-4"><b>Oração:</b> São Miguel, São Gabriel, São Rafael, rogai por nós.</p>' }] },
];
