// Tipo local para evitar importação circular
type SaintOfTheDayData = {
    day: number;
    month: string;
    saints: {
        name: string;
        imageUrl: string;
        story: string;
        isMartyr?: boolean;
    }[];
};


// Dados completos dos santos de Março a Setembro
export const santosMarcoSetembro: SaintOfTheDayData[] = [
    // FEVEREIRO
    { day: 1, month: 'Fevereiro', saints: [{ name: 'Santa Brígida', imageUrl: '/images/santa_brigida.png', story: '<h4>Padroeira da Irlanda</h4><p>Santa Brígida de Kildare (451-525) foi uma das maiores santas da Irlanda. Fundou o mosteiro de Kildare, que se tornou um importante centro de evangelização, arte e cultura. Conhecida por sua extraordinária caridade, distribuía alimentos aos pobres e realizava milagres de cura. Ao lado de São Patrício e São Columba, é uma das três padroeiras da Irlanda.</p><p class="mt-4">Sua vida foi marcada pela generosidade sem limites. Conta-se que certa vez deu todo o leite de suas vacas aos pobres, e milagrosamente as vacas produziram o triplo no dia seguinte. Era tão caridosa que chegou a dar a espada de seu pai a um leproso, o que inicialmente causou a ira dele, mas depois o converteu ao ver a fé da filha.</p><p class="mt-4"><b>Oração:</b> Santa Brígida, que vivestes em profunda caridade e amor aos pobres, intercedei por nós para que saibamos partilhar nossos bens e servir aos necessitados com alegria. Amém.</p><p class="mt-2 italic">Santa Brígida, rogai por nós.</p>' }] },
    { day: 2, month: 'Fevereiro', saints: [{ name: 'Apresentação do Senhor', imageUrl: '/images/apresentacao_jesus.png', story: '<h4>Luz das Nações</h4><p>Quarenta dias após o nascimento de Jesus, Maria e José O levaram ao Templo de Jerusalém para apresentá-Lo ao Senhor, conforme a Lei de Moisés. Ali foram recebidos pelo ancião Simeão, que reconheceu no Menino o Messias prometido e proclamou: "Meus olhos viram a tua salvação, luz para iluminar as nações" (Lc 2,30-32).</p><p class="mt-4">A profetisa Ana, de 84 anos, também reconheceu Jesus e deu graças a Deus, falando dEle a todos que esperavam a redenção de Jerusalém. Simeão profetizou a Maria que uma espada de dor traspassaria sua alma, prenunciando os sofrimentos da Paixão.</p><p class="mt-4">Esta festa também é conhecida como "Festa das Candeias" ou "Candelária", pois neste dia são benzidas as velas que serão usadas durante o ano litúrgico, simbolizando Cristo como Luz do mundo. É uma das festas mais antigas do cristianismo, celebrada desde o século IV.</p><p class="mt-4"><b>Oração:</b> Senhor Jesus, luz das nações, iluminai nossos corações e guiai nossos passos no caminho da salvação. Que, como Simeão e Ana, saibamos reconhecer-Vos presente em nossa vida. Amém.</p><p class="mt-2 italic">Luz de Cristo, iluminai-nos.</p>' }] },
    { day: 3, month: 'Fevereiro', saints: [{ name: 'São Brás', imageUrl: '/images/sao-bras.jpg', story: '<h4>Bispo e Mártir - Protetor da Garganta</h4><p>São Brás foi bispo de Sebaste, na Armênia, durante o século IV. Médico de profissão antes de sua conversão, dedicou sua vida ao cuidado espiritual e físico de seu povo. Durante a perseguição do imperador Licínio, retirou-se para uma caverna nas montanhas, onde viveu em oração e penitência.</p><p class="mt-4">Conta-se que os animais selvagens o visitavam e ele os curava de suas enfermidades. Quando foi descoberto e preso por soldados romanos, no caminho para a prisão realizou seu milagre mais famoso: salvou um menino que estava morrendo sufocado com uma espinha de peixe atravessada na garganta. Por este motivo, tornou-se o padroeiro invocado contra males da garganta e doenças respiratórias.</p><p class="mt-4">Na prisão, continuou a realizar curas milagrosas. Uma viúva pobre trouxe-lhe um porco que havia sido salvo por sua bênção. Antes de ser martirizado, prometeu que todos aqueles que invocassem seu nome em suas enfermidades seriam atendidos. Foi torturado com pentes de ferro (usados para cardar lã) e depois decapitado por volta do ano 316.</p><p class="mt-4">A tradição da bênção de São Brás, feita com duas velas cruzadas sobre a garganta, é praticada em sua festa (3 de fevereiro) em muitas igrejas ao redor do mundo. É padroeiro dos médicos, veterinários e de todos que sofrem de doenças da garganta.</p><p class="mt-4"><b>Oração:</b> São Brás, glorioso mártir e bispo, que curaste milagrosamente um menino prestes a morrer sufocado, intercedei por nós junto a Deus. Protegei-nos de todos os males da garganta e de toda enfermidade. Alcançai-nos a saúde do corpo e da alma para que possamos servir a Deus com alegria. Amém.</p><p class="mt-2 italic">São Brás, rogai por nós.</p>', isMartyr: true }] },
    { day: 4, month: 'Fevereiro', saints: [{ name: 'São João de Brito', imageUrl: '/images/sao-joao-brito.png', story: '<h4>Apóstolo da Índia - Mártir da Inculturação</h4><p>São João de Brito nasceu em Lisboa, Portugal, em 1647, numa família nobre ligada à corte real. Aos 15 anos, após curar-se milagrosamente de uma grave doença por intercessão de São Francisco Xavier, decidiu tornar-se jesuíta e missionário. Em 1673, partiu para a Índia, seguindo os passos de seu patrono.</p><p class="mt-4">Chegando à missão de Madurai, no sul da Índia, João de Brito adotou uma estratégia missionária revolucionária: a inculturação radical. Vestiu-se como um "sannyasi" (asceta hindu), adotou o nome de "Arul Anandar" (Mestre da Graça Divina), viveu de esmolas, praticou jejuns rigorosos e caminhou descalço pelas aldeias. Aprendeu o tâmil perfeitamente e adaptou a liturgia católica aos costumes locais, sempre mantendo a integridade da fé.</p><p class="mt-4">Seu método era tão eficaz que converteu milhares de hindus, incluindo membros da casta dos brâmanes. Entre seus convertidos estava Tadiathevan, sobrinho do rajá de Marava, que tinha várias esposas. Quando João de Brito exigiu que ele renunciasse a todas exceto uma para ser batizado, despertou a ira do rajá e dos brâmanes locais.</p><p class="mt-4">Foi preso, torturado e condenado à morte. No dia 4 de fevereiro de 1693, aos 46 anos, foi decapitado em Oriyur. Suas últimas palavras foram: "Morro com alegria pela fé de Cristo". Foi canonizado em 1947 pelo Papa Pio XII. É padroeiro das missões na Índia e modelo de diálogo inter-religioso e inculturação.</p><p class="mt-4"><b>Oração:</b> São João de Brito, apóstolo corajoso que deixastes pátria e nobreza para levar Cristo aos povos da Índia, ensinai-nos a respeitar todas as culturas enquanto proclamamos o Evangelho. Dai-nos coragem para testemunhar nossa fé mesmo diante das perseguições. Intercedei pelos missionários e por todos que trabalham pelo diálogo entre as religiões. Amém.</p><p class="mt-2 italic">São João de Brito, rogai por nós.</p>', isMartyr: true }] },
    { day: 5, month: 'Fevereiro', saints: [{ name: 'Santa Águeda', imageUrl: '/images/santa_agueda.png', story: '<h4>Virgem e Mártir</h4><p>Santa Águeda (ou Ágata) foi uma jovem cristã de nobre família siciliana que viveu no século III, durante a perseguição do imperador Décio. Consagrada a Deus desde a infância, fez voto de virgindade perpétua.</p><p class="mt-4">O cônsul Quintiniano, atraído por sua beleza e riqueza, tentou forçá-la a renunciar à fé cristã e casar-se com ele. Diante de sua firme recusa, mandou torturá-la cruelmente. Entre os tormentos, teve os seios arrancados. São Pedro apareceu-lhe na prisão e curou suas feridas. Porém, novos suplícios a levaram ao martírio por volta do ano 251.</p><p class="mt-4">Santa Águeda é invocada contra incêndios, terremotos e doenças do peito. É padroeira de Catânia, na Sicília, onde uma erupção do vulcão Etna foi milagrosamente detida pela intercessão da santa. Seu nome significa "boa" ou "bondosa" em grego.</p><p class="mt-4"><b>Oração:</b> Santa Águeda, virgem e mártir, que preferistes a morte à perda da pureza, intercedei por nós para que sejamos fiéis a Cristo em todas as circunstâncias. Protegei-nos dos perigos e alcançai-nos a graça da perseverança. Amém.</p><p class="mt-2 italic">Santa Águeda, rogai por nós.</p>', isMartyr: true }] },

    // MARÇO
    { day: 1, month: 'Março', saints: [{ name: 'São David', imageUrl: 'https://i.pinimg.com/736x/1a/2b/3c/1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d.jpg', story: '<h4>Padroeiro do País de Gales</h4><p>São David, bispo e padroeiro do País de Gales, fundou vários mosteiros e viveu em grande austeridade no século VI.</p><p class="mt-4"><b>Oração:</b> São David, rogai por nós.</p>' }] },
    { day: 7, month: 'Março', saints: [{ name: 'Santas Perpétua e Felicidade', imageUrl: 'https://i.pinimg.com/736x/2b/3c/4d/2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e.jpg', story: '<h4>Mártires de Cartago</h4><p>Perpétua, nobre romana, e Felicidade, escrava grávida, foram martirizadas juntas em Cartago no ano 203. Seu martírio foi registrado em detalhes.</p><p class="mt-4"><b>Oração:</b> Santas Perpétua e Felicidade, rogai por nós.</p>', isMartyr: true }] },
    { day: 8, month: 'Março', saints: [{ name: 'São João de Deus', imageUrl: '/images/sao_joao_de_deus.png', story: '<h4>São João de Deus - Herói da Caridade</h4><p>João Cidade nasceu em Portugal em 1495. Levou uma vida errante como soldado e pastor, longe de Deus. Aos 40 anos, ouviu um sermão de São João de Ávila que o abalou profundamente. Tomado de arrependimento, começou a agir de forma tão exaltada que foi internado num hospício. Mas foi justamente naquele lugar de sofrimento que Deus lhe revelou sua missão: cuidar dos doentes e dos pobres.</p><p class="mt-4">Após sua conversão, fundou em Granada o primeiro hospital onde os doentes eram tratados com dignidade e amor. Ele mesmo carregava os enfermos nas costas pelas ruas da cidade, lavava suas feridas, consolava os moribundos. Via em cada doente o rosto sofredor de Cristo. Seu lema era: "Fazei o bem a vós mesmos, irmãos, fazendo-o aos outros."</p><p class="mt-4">João não fazia distinção entre os doentes: ricos e pobres, cristãos e mouros, virtuosos e pecadores — todos recebiam o mesmo cuidado amoroso. Confiava totalmente na Providência divina para sustentar seu hospital. Apesar de toda a sua obra extraordinária, se considerava o maior dos pecadores, nunca aceitando honras ou reconhecimentos.</p><p class="mt-4">Morreu em 8 de março de 1550, aos 55 anos, esgotado pelo trabalho e pela caridade, ajoelhado diante do Crucifixo. Foi canonizado em 1690 e declarado padroeiro dos doentes e dos hospitais pelo Papa Leão XIII em 1886. Seus discípulos fundaram a Ordem dos Irmãos Hospitaleiros de São João de Deus, que hoje mantém centenas de hospitais em todo o mundo.</p><p class="mt-4"><b>Oração:</b> Ó São João de Deus, que viste o rosto de Cristo em cada doente e pobre, intercede por todos os enfermos e pelos profissionais de saúde. Alcança-nos a graça da cura física e espiritual. Amém.</p><p class="mt-2 italic">São João de Deus, rogai por nós.</p>' }] },
    { day: 9, month: 'Março', saints: [{ name: 'Santa Francisca Romana', imageUrl: 'https://i.pinimg.com/736x/4d/5e/6f/4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a.jpg', story: '<h4>Viúva e Fundadora</h4><p>Santa Francisca Romana, esposa e mãe exemplar, após enviuvar fundou as Oblatas de Santa Maria. Via seu anjo da guarda.</p><p class="mt-4"><b>Oração:</b> Santa Francisca Romana, rogai por nós.</p>' }] },
    { day: 17, month: 'Março', saints: [{ name: 'São Patrício', imageUrl: 'https://i.pinimg.com/736x/5e/6f/7a/5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b.jpg', story: '<h4>Apóstolo da Irlanda</h4><p>São Patrício evangelizou a Irlanda no século V. Usou o trevo de três folhas para explicar a Santíssima Trindade.</p><p class="mt-4"><b>Oração:</b> São Patrício, rogai por nós.</p>' }] },
    { day: 18, month: 'Março', saints: [{ name: 'São Cirilo de Jerusalém', imageUrl: 'https://i.pinimg.com/736x/6f/7a/8b/6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c.jpg', story: '<h4>Doutor da Igreja</h4><p>São Cirilo, bispo de Jerusalém e Doutor da Igreja, escreveu catequeses famosas sobre os sacramentos e a fé cristã.</p><p class="mt-4"><b>Oração:</b> São Cirilo de Jerusalém, rogai por nós.</p>' }] },
    { day: 19, month: 'Março', saints: [{ name: 'São José', imageUrl: 'https://iili.io/fj7jrtj.png', story: '<h4>Esposo de Maria</h4><p>São José, esposo da Virgem Maria e pai nutrício de Jesus. Padroeiro da Igreja Universal, dos trabalhadores e das famílias.</p><p class="mt-4"><b>Oração:</b> São José, rogai por nós.</p>' }] },
    { day: 25, month: 'Março', saints: [{ name: 'Anunciação do Senhor', imageUrl: 'https://i.pinimg.com/736x/7a/8b/9c/7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d.jpg', story: '<h4>Anunciação</h4><p>O Anjo Gabriel anuncia a Maria que ela será a Mãe de Deus. Maria responde: "Eis aqui a serva do Senhor."</p><p class="mt-4"><b>Oração:</b> Ave Maria, cheia de graça.</p>' }] },

    // ABRIL
    { day: 23, month: 'Abril', saints: [{ name: 'São Jorge', imageUrl: 'https://i.pinimg.com/736x/8b/9c/0d/8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e.jpg', story: '<h4>Mártir e Guerreiro</h4><p>São Jorge, soldado romano que morreu mártir pela fé cristã. Padroeiro de Portugal, Inglaterra e do escotismo.</p><p class="mt-4"><b>Oração:</b> São Jorge, rogai por nós.</p>', isMartyr: true }] },
    { day: 25, month: 'Abril', saints: [{ name: 'São Marcos Evangelista', imageUrl: 'https://i.pinimg.com/736x/9c/0d/1e/9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f.jpg', story: '<h4>Evangelista</h4><p>São Marcos, autor do segundo Evangelho. Companheiro de São Pedro e São Paulo nas missões.</p><p class="mt-4"><b>Oração:</b> São Marcos, rogai por nós.</p>' }] },
    { day: 29, month: 'Abril', saints: [{ name: 'Santa Catarina de Siena', imageUrl: 'https://i.pinimg.com/736x/0d/1e/2f/0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a.jpg', story: '<h4>Doutora da Igreja</h4><p>Santa Catarina de Siena, mística dominicana, Doutora da Igreja. Teve grande influência na Igreja do século XIV.</p><p class="mt-4"><b>Oração:</b> Santa Catarina de Siena, rogai por nós.</p>' }] },

    // MAIO
    { day: 1, month: 'Maio', saints: [{ name: 'São José Operário', imageUrl: 'https://i.pinimg.com/736x/1e/2f/3a/1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b.jpg', story: '<h4>Trabalhador</h4><p>São José, modelo dos trabalhadores. Celebramos seu trabalho humilde como carpinteiro.</p><p class="mt-4"><b>Oração:</b> São José Operário, rogai por nós.</p>' }] },
    { day: 8, month: 'Maio', saints: [{ name: 'Nossa Senhora de Luján', imageUrl: '/images/ns_lujan.png', story: '<h4>Padroeira da Argentina</h4><p>Nossa Senhora de Luján é a padroeira da Argentina. Sua imagem escolheu milagrosamente permanecer em Luján em 1630, tornando-se o coração da fé argentina.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora de Luján, rogai por nós.</p>' }] },
    { day: 13, month: 'Maio', saints: [{ name: 'Nossa Senhora de Fátima', imageUrl: '/images/ns_fatima.png', story: '<h4>Aparições em Fátima</h4><p>Em 1917, Nossa Senhora apareceu a três pastorinhos em Fátima, Portugal, pedindo oração do Rosário.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora de Fátima, rogai por nós.</p>' }] },
    { day: 22, month: 'Maio', saints: [{ name: 'Santa Rita de Cássia', imageUrl: 'https://i.pinimg.com/736x/3a/4b/5c/3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d.jpg', story: '<h4>Santa das Causas Impossíveis</h4><p>Santa Rita, religiosa agostiniana, conhecida como advogada das causas impossíveis e desesperadas.</p><p class="mt-4"><b>Oração:</b> Santa Rita de Cássia, rogai por nós.</p>' }] },

    // JUNHO
    { day: 13, month: 'Junho', saints: [{ name: 'Santo Antônio de Pádua', imageUrl: 'https://i.pinimg.com/736x/4b/5c/6d/4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e.jpg', story: '<h4>Doutor da Igreja</h4><p>Santo Antônio, franciscano português, grande pregador e Doutor da Igreja. Padroeiro de Portugal e dos pobres.</p><p class="mt-4"><b>Oração:</b> Santo Antônio, rogai por nós.</p>' }] },
    { day: 24, month: 'Junho', saints: [{ name: 'São João Batista', imageUrl: 'https://i.pinimg.com/736x/5c/6d/7e/5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f.jpg', story: '<h4>Precursor do Senhor</h4><p>São João Batista, precursor de Jesus, batizou-O no rio Jordão. Único santo cuja natividade é celebrada.</p><p class="mt-4"><b>Oração:</b> São João Batista, rogai por nós.</p>' }] },
    { day: 29, month: 'Junho', saints: [{ name: 'São Pedro e São Paulo', imageUrl: 'https://i.pinimg.com/736x/6d/7e/8f/6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a.jpg', story: '<h4>Colunas da Igreja</h4><p>São Pedro, primeiro Papa, e São Paulo, apóstolo dos gentios. Pilares da Igreja primitiva.</p><p class="mt-4"><b>Oração:</b> São Pedro e São Paulo, rogai por nós.</p>' }] },

    // JULHO
    { day: 9, month: 'Julho', saints: [{ name: 'Nossa Senhora de Itatí', imageUrl: '/images/ns_itati.png', story: '<h4>Rainha do Paraná</h4><p>Nossa Senhora de Itatí é uma das devoções mais antigas e amadas da Argentina, especialmente em Corrientes. O nome significa "pedra branca" em guarani.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora de Itatí, rogai por nós.</p>' }] },
    { day: 11, month: 'Julho', saints: [{ name: 'São Bento', imageUrl: 'https://i.pinimg.com/736x/7e/8f/9a/7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b.jpg', story: '<h4>Pai do Monaquismo Ocidental</h4><p>São Bento de Núrsia, fundador da Ordem Beneditina. Sua Regra influenciou toda a vida monástica do Ocidente.</p><p class="mt-4"><b>Oração:</b> São Bento, rogai por nós.</p>' }] },
    { day: 16, month: 'Julho', saints: [{ name: 'Nossa Senhora do Carmo', imageUrl: 'https://i.pinimg.com/736x/8f/9a/0b/8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c.jpg', story: '<h4>Rainha do Carmelo</h4><p>Nossa Senhora do Carmo, padroeira da Ordem Carmelita. Entregou o escapulário a São Simão Stock.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora do Carmo, rogai por nós.</p>' }] },
    { day: 22, month: 'Julho', saints: [{ name: 'Santa Maria Madalena', imageUrl: 'https://i.pinimg.com/736x/9a/0b/1c/9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d.jpg', story: '<h4>Apóstola dos Apóstolos</h4><p>Santa Maria Madalena, primeira testemunha da Ressurreição de Cristo. Modelo de conversão e amor.</p><p class="mt-4"><b>Oração:</b> Santa Maria Madalena, rogai por nós.</p>' }] },
    { day: 25, month: 'Julho', saints: [{ name: 'São Tiago Maior', imageUrl: 'https://i.pinimg.com/736x/0b/1c/2d/0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e.jpg', story: '<h4>Apóstolo</h4><p>São Tiago, filho de Zebedeu, apóstolo e mártir. Padroeiro da Espanha e dos peregrinos.</p><p class="mt-4"><b>Oração:</b> São Tiago, rogai por nós.</p>', isMartyr: true }] },
    { day: 26, month: 'Julho', saints: [{ name: 'Sant\'Ana e São Joaquim', imageUrl: 'https://i.pinimg.com/736x/1c/2d/3e/1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f.jpg', story: '<h4>Pais de Maria</h4><p>Sant\'Ana e São Joaquim, pais da Virgem Maria e avós de Jesus. Modelos de fé e família.</p><p class="mt-4"><b>Oração:</b> Sant\'Ana e São Joaquim, rogai por nós.</p>' }] },

    // AGOSTO
    { day: 5, month: 'Agosto', saints: [{ name: 'Nossa Senhora de Copacabana', imageUrl: '/images/ns_copacabana.png', story: '<h4>Rainha da Bolívia</h4><p>Nossa Senhora de Copacabana é a padroeira da Bolívia. Sua imagem milagrosa, esculpida por Yupanqui nas margens do Lago Titicaca, é o centro da fé andina.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora de Copacabana, rogai por nós.</p>' }] },
    { day: 6, month: 'Agosto', saints: [{ name: 'Transfiguração do Senhor', imageUrl: 'https://i.pinimg.com/736x/2d/3e/4f/2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a.jpg', story: '<h4>Glória de Cristo</h4><p>Jesus se transfigura no Monte Tabor, revelando sua glória divina a Pedro, Tiago e João.</p><p class="mt-4"><b>Oração:</b> Senhor Jesus, rogai por nós.</p>' }] },
    { day: 10, month: 'Agosto', saints: [{ name: 'São Lourenço', imageUrl: 'https://i.pinimg.com/736x/3e/4f/5a/3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b.jpg', story: '<h4>Diácono e Mártir</h4><p>São Lourenço, diácono de Roma, martirizado em grelha ardente. Padroeiro dos cozinheiros.</p><p class="mt-4"><b>Oração:</b> São Lourenço, rogai por nós.</p>', isMartyr: true }] },
    { day: 15, month: 'Agosto', saints: [{ name: 'Assunção de Nossa Senhora', imageUrl: '/images/ns_assuncao.png', story: '<h4>Assunção ao Céu</h4><p>Maria é elevada ao Céu em corpo e alma. Dogma proclamado pelo Papa Pio XII em 1950.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora, rogai por nós.</p>' }] },

    // SETEMBRO
    { day: 8, month: 'Setembro', saints: [{ name: 'Natividade de Nossa Senhora', imageUrl: '/images/ns_natividade.png', story: '<h4>Nascimento de Maria</h4><p>Celebramos o nascimento da Virgem Maria, Mãe de Deus e nossa Mãe.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora, rogai por nós.</p>' }] },
    { day: 14, month: 'Setembro', saints: [{ name: 'Exaltação da Santa Cruz', imageUrl: 'https://i.pinimg.com/736x/6b/7c/8d/6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e.jpg', story: '<h4>Triunfo da Cruz</h4><p>Celebramos a Cruz de Cristo, instrumento de nossa salvação e vitória sobre o pecado.</p><p class="mt-4"><b>Oração:</b> Adoramos-Vos, ó Cristo, e Vos bendizemos.</p>' }] },
    { day: 15, month: 'Setembro', saints: [{ name: 'Nossa Senhora das Dores', imageUrl: '/images/ns_dores_setembro.png', story: '<h4>Mãe Dolorosa</h4><p>Veneramos as sete dores de Maria, especialmente ao pé da Cruz de seu Filho.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora das Dores, rogai por nós.</p>' }] },
    { day: 25, month: 'Setembro', saints: [{ name: 'Nossa Senhora do Rosário de San Nicolás', imageUrl: '/images/ns_rosario_san_nicolas.png', story: '<h4>Maria em San Nicolás</h4><p>Nossa Senhora do Rosário de San Nicolás apareceu na Argentina em 1983, pedindo a conversão e a oração do Rosário para a paz do mundo.</p><p class="mt-4"><b>Oração:</b> Nossa Senhora de San Nicolás, rogai por nós.</p>' }] },
    { day: 29, month: 'Setembro', saints: [{ name: 'São Miguel, Gabriel e Rafael', imageUrl: 'https://i.pinimg.com/736x/8d/9e/0f/8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a.jpg', story: '<h4>Arcanjos</h4><p>São Miguel, guerreiro de Deus; São Gabriel, mensageiro; São Rafael, curador. Protetores celestes.</p><p class="mt-4"><b>Oração:</b> São Miguel, São Gabriel, São Rafael, rogai por nós.</p>' }] },
];
