"use client";

import React, { useState, useEffect, useRef } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogClose } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { BookOpen, X } from "lucide-react";
import Image from "next/image";

interface MarianDevotion {
    id: string;
    name: string;
    date: string;
    month: string;
    imageUrl: string;
    description: string;
    fullDescription?: string;
    novenaId?: string;
}

export function MarianGallery() {
    const devotions: MarianDevotion[] = [
        // JANEIRO
        { id: "mae_deus", name: "Santa Maria, Mãe de Deus", date: "01/01", month: "Janeiro", imageUrl: "/images/santa-maria-mae-de-deus.jpg", description: "Solenidade mariana mais antiga e importante, celebrada na Oitava do Natal (Theotokos)", fullDescription: "A Solenidade de Santa Maria, Mãe de Deus (Theotokos) é celebrada no dia 1º de janeiro, dentro da Oitava do Natal. É a festa mariana mais antiga da Igreja e celebra o dogma proclamado no Concílio de Éfeso (431 d.C.) de que Maria é verdadeiramente Mãe de Deus, pois deu à luz Jesus Cristo, que é verdadeiro Deus e verdadeiro homem." },
        { id: "cana", name: "Nossa Senhora de Caná", date: "06/01", month: "Janeiro", imageUrl: "/images/ns_cana.png", description: "Lembrada na Epifania, celebrando a intercessão de Maria nas Bodas de Caná", fullDescription: "Nas Bodas de Caná, Maria demonstrou sua poderosa intercessão junto a Jesus. Ao perceber que faltava vinho, ela disse aos servos: 'Fazei tudo o que Ele vos disser'. Este primeiro milagre de Jesus, realizado a pedido de sua Mãe, manifesta o poder da intercessão mariana e nos ensina a confiar em Maria como medianeira de todas as graças." },
        { id: "bom_parto", name: "Nossa Senhora do Bom Parto", date: "Último domingo", month: "Janeiro", imageUrl: "https://i.pinimg.com/1200x/cc/80/b9/cc80b9f6815e1ec29ad8815d63103fbb.jpg", description: "Devoção muito antiga, ligada à proteção das mães", fullDescription: "Esta devoção remonta aos primeiros séculos do cristianismo e invoca Maria como protetora das gestantes e mães. A imagem representa Maria grávida, prestes a dar à luz o Salvador. É especialmente invocada por mulheres que esperam um filho, pedindo proteção durante a gravidez e um parto seguro. A devoção nos lembra que Maria também passou pela experiência da maternidade humana." },

        // FEVEREIRO
        { id: "candeias", name: "Nossa Senhora das Candeias", date: "02/02", month: "Fevereiro", imageUrl: "/images/ns_candeias.png", description: "Apresentação do Senhor no templo. Também Nossa Senhora dos Navegantes", fullDescription: "Celebrada 40 dias após o Natal, esta festa comemora a Apresentação de Jesus no Templo, quando Maria e José levaram o Menino para ser consagrado a Deus. O profeta Simeão reconheceu em Jesus a 'Luz para iluminar as nações', daí o nome 'Candeias' (velas). É também invocada como Nossa Senhora dos Navegantes, especialmente no Brasil, onde grandes procissões marítimas são realizadas." },
        { id: "lourdes", name: "Nossa Senhora de Lourdes", date: "11/02", month: "Fevereiro", imageUrl: "/images/ns_lourdes.png", description: "Padroeira dos enfermos. Aparições a Santa Bernadette em 1858", fullDescription: "Entre 11 de fevereiro e 16 de julho de 1858, a Virgem Maria apareceu 18 vezes a Bernadette Soubirous, uma menina pobre e analfabeta de 14 anos, na gruta de Massabielle, às margens do rio Gave, em Lourdes, França. Maria se apresentou como 'Que soy era Immaculada Councepciou' (Eu sou a Imaculada Conceição, em dialeto local), confirmando o dogma proclamado pelo Papa Pio IX apenas quatro anos antes, em 1854. Durante as aparições, Maria pediu oração, penitência pela conversão dos pecadores e a construção de uma capela no local. Na nona aparição, em 25 de fevereiro, Maria indicou uma fonte de água que brotou milagrosamente e se tornou famosa pelas curas extraordinárias. Lourdes é hoje o segundo maior centro de peregrinação católica do mundo, recebendo cerca de 6 milhões de peregrinos anualmente, incluindo milhares de enfermos que buscam cura física e espiritual. A Igreja Católica reconheceu oficialmente 70 milagres após rigorosa investigação médica e científica, mas milhares de curas inexplicadas foram relatadas ao longo dos anos. O Bureau Médico de Lourdes documenta meticulosamente cada caso. Nossa Senhora de Lourdes é padroeira dos enfermos, dos médicos católicos e de inúmeras instituições de saúde em todo o mundo. A devoção nos ensina que Maria é refúgio e consolo para todos os que sofrem, e que a verdadeira cura começa na alma. Santa Bernadette, que se tornou freira e morreu aos 35 anos, foi canonizada em 1933. Seu corpo permanece incorrupto em Nevers, França." },
        { id: "desterro", name: "Nossa Senhora do Desterro", date: "17/02", month: "Fevereiro", imageUrl: "/images/ns_desterro.png", description: "Lembra a fuga da Sagrada Família para o Egito. Proteção para a casa, viagens e emigrantes.", fullDescription: "Esta devoção recorda a fuga da Sagrada Família para o Egito, quando José foi avisado em sonho para fugir da perseguição de Herodes. Maria, com o Menino Jesus nos braços, enfrentou o exílio e a incerteza, tornando-se padroeira de todos os refugiados, emigrantes e viajantes. É invocada para proteção da casa, das viagens e de todos que vivem longe de sua terra natal." },

        // MARÇO
        { id: "anunciacao", name: "Nossa Senhora da Anunciação", date: "25/03", month: "Março", imageUrl: "/images/ns_anunciacao.png", description: "Marca o 'Sim' (Fiat) de Maria à Encarnação", fullDescription: "A Anunciação celebra o momento em que o Arcanjo Gabriel anunciou a Maria que ela seria a Mãe de Deus. Seu 'Fiat' ('Faça-se') foi o sim que mudou a história da humanidade, permitindo a Encarnação do Verbo. Esta solenidade, celebrada nove meses antes do Natal, nos ensina a importância da obediência confiante à vontade de Deus." },
        { id: "dores_marco", name: "Nossa Senhora das Dores", date: "Semana Santa", month: "Março", imageUrl: "/images/ns_dores_semana_santa.png", description: "Celebrada intensamente na Semana Santa", fullDescription: "Durante a Semana Santa, contemplamos Maria ao pé da Cruz, compartilhando as dores de seu Filho. As sete dores de Maria incluem a profecia de Simeão, a fuga para o Egito, a perda de Jesus no templo, o encontro no caminho do Calvário, a crucifixão, a descida da cruz e o sepultamento. Maria é modelo de fé e fortaleza no sofrimento." },

        // ABRIL
        { id: "penha", name: "Nossa Senhora da Penha", date: "08/04", month: "Abril", imageUrl: "/images/ns_penha.png", description: "Padroeira do Espírito Santo e de grande devoção no Rio de Janeiro", fullDescription: "O Santuário de Nossa Senhora da Penha, no Rio de Janeiro, é um dos mais antigos do Brasil, fundado em 1635. A devoção começou quando um devoto português foi curado de uma doença grave após prometer construir uma capela no alto de um rochedo. A subida de 382 degraus é feita por milhares de romeiros anualmente, demonstrando fé e penitência." },
        { id: "bom_conselho", name: "Nossa Senhora do Bom Conselho", date: "26/04", month: "Abril", imageUrl: "/images/ns_bom_conselho.png", description: "Padroeira de muitas prefeituras e advogada para tomadas de decisão difíceis.", fullDescription: "Esta devoção tem origem em Genazzano, Itália, onde uma imagem de Maria apareceu milagrosamente em 1467. Maria é invocada como 'Mãe do Bom Conselho' por aqueles que enfrentam decisões difíceis e buscam a sabedoria divina. É especialmente venerada por estudantes, políticos e todos que precisam de discernimento." },

        // MAIO
        { id: "estrela", name: "Nossa Senhora da Estrela", date: "08/05", month: "Maio", imageUrl: "/images/ns_estrela.png", description: "Também Nossa Senhora de Luján, padroeira da Argentina", fullDescription: "Nossa Senhora de Luján é a padroeira da Argentina. Em 1630, uma imagem de Maria estava sendo transportada quando a carreta parou misteriosamente e não conseguia mais se mover. Interpretando isso como um sinal divino, construíram uma capela no local. Maria é chamada de 'Estrela' porque guia os fiéis no caminho da salvação." },
        { id: "fatima", name: "Nossa Senhora de Fátima", date: "13/05", month: "Maio", imageUrl: "/images/ns_fatima.png", description: "Uma das devoções mais populares no Brasil", fullDescription: "Entre 13 de maio e 13 de outubro de 1917, Nossa Senhora apareceu seis vezes a três pastorinhos - Lúcia dos Santos (10 anos), Francisco Marto (9 anos) e Jacinta Marto (7 anos) - na Cova da Iria, em Fátima, Portugal. Maria se apresentou como 'Nossa Senhora do Rosário' e pediu oração do Rosário todos os dias pela paz no mundo (a Primeira Guerra Mundial estava em curso), penitência pela conversão dos pecadores e consagração ao seu Imaculado Coração. As aparições culminaram com o famoso Milagre do Sol em 13 de outubro de 1917, presenciado por aproximadamente 70 mil pessoas, incluindo jornalistas céticos e ateus. O sol pareceu desprender-se do céu, dançar, mudar de cores e lançar-se sobre a multidão aterrorizada, secando instantaneamente as roupas e o solo encharcados pela chuva torrencial. O fenômeno durou cerca de 10 minutos e foi visto a quilômetros de distância. Os três segredos de Fátima, revelados por Lúcia, incluem: uma visão aterradora do inferno, a profecia sobre o fim da Primeira Guerra Mundial e o início da Segunda se a humanidade não se convertesse, a conversão da Rússia (que estava se tornando comunista), e o mistério do 'Bispo vestido de branco' que caminha entre cadáveres de mártires (interpretado como o atentado ao Papa João Paulo II em 13 de maio de 1981, exatamente 64 anos após a primeira aparição). Francisco e Jacinta morreram jovens, vítimas da gripe espanhola em 1919 e 1920, e foram canonizados em 2017. Lúcia tornou-se freira carmelita e faleceu em 2005 aos 97 anos. Fátima é uma das devoções marianas mais populares do mundo, especialmente no Brasil, onde milhões de fiéis celebram o dia 13 de cada mês com procissões, orações e vigílias. O Santuário de Fátima recebe mais de 6 milhões de peregrinos anualmente." },
        { id: "auxiliadora", name: "Nossa Senhora Auxiliadora", date: "24/05", month: "Maio", imageUrl: "/images/ns_auxiliadora.png", description: "Padroeira da Família Salesiana, de Goiânia e de Palmas", fullDescription: "O título 'Auxiliadora dos Cristãos' foi dado a Maria pelo Papa Pio V após a vitória de Lepanto. São João Bosco tinha profunda devoção a Nossa Senhora Auxiliadora e construiu uma basílica em sua honra em Turim. É a padroeira dos salesianos e de muitas cidades brasileiras, sendo invocada como auxilio poderoso em todas as necessidades." },
        { id: "caravaggio", name: "Nossa Senhora de Caravaggio", date: "26/05", month: "Maio", imageUrl: "/images/ns_caravaggio.png", description: "Grande devoção no sul do Brasil (imigrantes italianos)", fullDescription: "Em 26 de maio de 1432, Nossa Senhora apareceu a Giannetta Varoli (ou Giannetta de' Vacchi), uma humilde camponesa de 32 anos, no campo de Mazzolengo, próximo à cidade de Caravaggio, na Lombardia, Itália. Maria estava acompanhada de São João Batista e apareceu com grande esplendor, vestida de azul e branco. Ela lamentou profundamente os pecados do povo, especialmente a blasfêmia, a profanação do domingo e a falta de oração, e pediu penitência, jejum às sextas-feiras, oração e a construção de uma igreja no local da aparição. No exato lugar onde Maria pisou, brotou uma fonte de água cristalina que até hoje é procurada por peregrinos de todo o mundo, sendo atribuídas a ela inúmeras curas milagrosas. A magnífica Basílica de Santa Maria del Fonte foi construída no local e tornou-se um importante centro de peregrinação na Itália. A devoção foi trazida ao Brasil pelos imigrantes italianos no final do século XIX e início do século XX, enraizando-se profundamente nos estados do sul, especialmente Rio Grande do Sul, Santa Catarina e Paraná, onde há forte presença de descendentes italianos. Grandes romarias são realizadas anualmente em 26 de maio, reunindo dezenas de milhares de fiéis que mantêm viva a fé, as tradições e a cultura de seus antepassados. A festa de Nossa Senhora de Caravaggio é marcada por procissões solenes, missas festivas em italiano e português, apresentações de corais, danças típicas, gastronomia italiana e manifestações da cultura ínalo-brasileira, sendo um dos maiores e mais emocionantes eventos religiosos e culturais das comunidades de descendência italiana no Brasil. Muitos santuários e capelas dedicados a Nossa Senhora de Caravaggio foram construídos no sul do Brasil, perpetuando esta bela devoção mariana." },
        { id: "visitacao", name: "Visitação de Nossa Senhora", date: "31/05", month: "Maio", imageUrl: "/images/visitacao_ns.png", description: "Festa que encerra o mês de Maria, lembrando a visita a Santa Isabel", fullDescription: "Após a Anunciação, Maria foi apressadamente visitar sua prima Isabel, que estava grávida de João Batista. Ao ouvir a saudação de Maria, Isabel foi cheia do Espírito Santo e exclamou: 'Bendita és tu entre as mulheres!'. Maria respondeu com o Magnificat, o cântico de louvor que exalta a humildade e a misericórdia de Deus. Esta festa nos ensina a caridade e o serviço ao próximo." },

        // JUNHO
        { id: "imaculado_coracao", name: "Imaculado Coração de Maria", date: "Sábado após Sagrado Coração", month: "Junho", imageUrl: "/images/imaculado_coracao_maria.png", description: "Memória obrigatória", fullDescription: "A devoção ao Imaculado Coração de Maria foi especialmente promovida pelas aparições de Fátima em 1917, quando Nossa Senhora pediu a consagração da Rússia e do mundo ao seu Imaculado Coração. O Papa Pio XII instituiu esta festa em 1944, celebrada no sábado seguinte à Solenidade do Sagrado Coração de Jesus. O Coração de Maria representa seu amor materno por todos os seus filhos, sua compaixão pelos pecadores e sua união perfeita com a vontade de Deus. É um coração que nunca foi manchado pelo pecado e que permanece sempre aberto para acolher aqueles que a ela recorrem." },
        { id: "consolata", name: "Nossa Senhora da Consolata", date: "20/06", month: "Junho", imageUrl: "/images/ns_consolata.png", description: "Padroeira dos missionários da Consolata e de Turim. Muito venerada em São Paulo.", fullDescription: "O Santuário de Nossa Senhora Consolata em Turim, Itália, remonta ao século V. A devoção ganhou novo impulso quando o Beato José Allamano fundou os Missionários e Missionárias da Consolata em 1901. A imagem representa Maria como 'Consoladora dos Aflitos', oferecendo conforto espiritual a todos que sofrem. No Brasil, especialmente em São Paulo, a devoção foi trazida pelos imigrantes italianos e pelos missionários da Consolata. Maria Consolata é invocada em momentos de tristeza, angústia e dificuldades, sendo conhecida por sua poderosa intercessão nas causas mais difíceis." },
        { id: "perpetuo_socorro", name: "Nossa Senhora do Perpétuo Socorro", date: "27/06", month: "Junho", imageUrl: "/images/ns_perpetuo_socorro.png", description: "Título oriental (ícone bizantino) difundido pelos Redentoristas", fullDescription: "O ícone de Nossa Senhora do Perpétuo Socorro é uma das imagens marianas mais veneradas no mundo. De origem bizantina, provavelmente do século XIII ou XIV, mostra Maria segurando o Menino Jesus, que se agarra à sua mãe ao ver os anjos com os instrumentos da Paixão. O ícone foi confiado aos Padres Redentoristas pelo Papa Pio IX em 1866, que o expuseram para veneração pública em Roma. A devoção se espalhou rapidamente pelo mundo, com milhões de fiéis recorrendo a Maria sob este título. O nome 'Perpétuo Socorro' expressa a confiança de que Maria nunca abandona seus filhos e está sempre pronta a socorrê-los em suas necessidades espirituais e materiais." },

        // JULHO
        { id: "rainha_paz", name: "Rainha da Paz", date: "09/07", month: "Julho", imageUrl: "https://iili.io/fjEnxxn.jpg", description: "Muito invocada para o fim de guerras e conflitos familiares.", fullDescription: "Nossa Senhora Rainha da Paz é especialmente venerada em Medjugorje, Bósnia-Herzegovina, onde desde 1981 são relatadas aparições marianas. Maria se apresenta como 'Rainha da Paz' e pede oração, jejum, conversão e reconciliação. Embora as aparições ainda estejam sob investigação da Igreja, a devoção se espalhou pelo mundo todo. Maria é invocada como Rainha da Paz não apenas para o fim de guerras e conflitos entre nações, mas também para trazer paz aos corações, às famílias e às comunidades. Ela nos ensina que a verdadeira paz começa na conversão do coração e na reconciliação com Deus e com o próximo." },
        { id: "carmo", name: "Nossa Senhora do Carmo", date: "16/07", month: "Julho", imageUrl: "https://iili.io/fjGdG4I.jpg", description: "Festa do Escapulário. Padroeira de Recife", fullDescription: "Em 16 de julho de 1251, Nossa Senhora apareceu a São Simão Stock, superior geral da Ordem dos Carmelitas, em Cambridge, Inglaterra, durante um momento de grande tribulação da Ordem. Maria apareceu com grande esplendor, cercada de anjos, e entregou-lhe o Escapulário do Carmo (dois pedaços de tecido marrom unidos por cordões), fazendo a famosa promessa: 'Quem morrer revestido dele não padecerá o fogo eterno'. Esta promessa, conhecida como 'privilégio sabatino', foi posteriormente confirmada e ampliada pelo Papa João XXII em 1322, que declarou ter recebido uma revelação de Maria prometendo que ela libertaria do purgatório no primeiro sábado após a morte aqueles que usassem o escapulário com devoção, vivessem castamente segundo seu estado de vida, rezassem o Ofício Divino (ou o Rosário) e observassem os jejuns da Igreja. O Escapulário do Carmo tornou-se um dos sacramentais mais difundidos e amados da Igreja Católica, sendo usado por milhões de fiéis em todo o mundo, incluindo numerosos santos como São João Bosco, Santa Teresinha do Menino Jesus, São Padre Pio e São João Paulo II. Nossa Senhora do Carmo é padroeira de Recife, da Bolívia, do Chile e de inúmeras outras cidades e instituições. A devoção carmelita enfatiza a vida de oração contemplativa, a união íntima com Deus e o silêncio interior, seguindo o exemplo do profeta Elias que viveu no Monte Carmelo. Usar o escapulário é um sinal visível de consagração a Maria e de compromisso com uma vida cristã autêntica, marcada pela oração, penitência e caridade. A festa de Nossa Senhora do Carmo, em 16 de julho, é celebrada com grande solenidade em todo o mundo católico." },
        { id: "santana", name: "Sant'Ana (Mãe de Maria)", date: "26/07", month: "Julho", imageUrl: "/images/santa_ana.png", description: "Devoção intrinsecamente ligada à 'Menina Maria'", fullDescription: "Sant'Ana, mãe de Maria e avó de Jesus, é venerada desde os primeiros séculos do cristianismo. Embora não seja mencionada nos Evangelhos canônicos, a tradição cristã, baseada no Protoevangelho de Tiago, conta que Ana e seu esposo Joaquim eram um casal piedoso e estéril que recebeu de Deus o dom de uma filha: Maria Santíssima. Sant'Ana é padroeira das mães, avós, mulheres grávidas e de diversas profissões. Sua festa é celebrada com grande devoção em todo o mundo católico, especialmente no Brasil, onde muitas cidades e paróquias levam seu nome. A imagem de Sant'Ana ensinando Maria a ler as Escrituras é um símbolo da educação cristã e da transmissão da fé de geração em geração." },

        // AGOSTO
        { id: "anjos", name: "Nossa Senhora dos Anjos", date: "02/08", month: "Agosto", imageUrl: "/images/ns_anjos.png", description: "Festa franciscana do perdão de Assis (Porciúncula)", fullDescription: "A festa de Nossa Senhora dos Anjos, também conhecida como Perdão de Assis ou Porciúncula, comemora a indulência plenária concedida por Jesus a pedido de São Francisco de Assis. Em 1216, Francisco teve uma visão de Jesus e Maria na pequena capela da Porciúncula, onde lhe foi concedida uma indulência especial para todos que visitassem aquela igreja arrependidos e confessados. Esta graça foi estendida a todas as igrejas franciscanas e paroquiais no dia 2 de agosto. A devoção nos lembra da misericórdia infinita de Deus e da intercessação maternal de Maria, que sempre nos conduz ao perdão e à reconciliação." },
        { id: "saude_agosto", name: "N.S. da Saúde", date: "05/08", month: "Agosto", imageUrl: "/images/ns_saude_agosto.png", description: "Invocada contra pestes e doenças. Muitas igrejas históricas no Brasil com este título.", fullDescription: "A devoção a Nossa Senhora da Saúde tem raízes profundas na história da Igreja, especialmente em momentos de epidemias e pestes. No Brasil, muitas igrejas coloniais foram dedicadas a este título mariano, refletindo a confiança do povo na intercessação de Maria para a cura de doenças físicas e espirituais. Maria é invocada como 'Saúde dos Enfermos' na Ladainha de Nossa Senhora, sendo uma das advocações mais antigas e universais. A devoção nos ensina a confiar na providência divina em tempos de enfermidade e a buscar em Maria o conforto e a esperança de cura, sempre submetendo-nos à vontade de Deus." },
        { id: "neves", name: "Nossa Senhora das Neves", date: "05/08", month: "Agosto", imageUrl: "/images/ns_neves.png", description: "Padroeira da Paraíba (João Pessoa)", fullDescription: "A devoção a Nossa Senhora das Neves tem origem em um milagre ocorrido em Roma no século IV. Segundo a tradição, Maria apareceu em sonho a um casal nobre e ao Papa Libério, pedindo que construíssem uma igreja em sua honra no Monte Esquilino. Como sinal, nevou milagrosamente naquele local em pleno verão romano, no dia 5 de agosto de 358. Ali foi construída a Basílica de Santa Maria Maior, uma das quatro basílicas papais de Roma. No Brasil, Nossa Senhora das Neves é padroeira da Paraíba e de João Pessoa, sendo venerada com grande devoção. A neve, símbolo de pureza, nos lembra da imaculada virgindade de Maria e de sua intercessão poderosa junto a Deus." },
        { id: "assuncao", name: "Assunção de Nossa Senhora", date: "15/08", month: "Agosto", imageUrl: "/images/ns_assuncao.png", description: "Solenidade. Elevação ao Céu em corpo e alma", fullDescription: "A Assunção de Nossa Senhora é o dogma de fé que proclama que Maria Santíssima, ao fim de sua vida terrena, foi elevada ao Céu em corpo e alma pela glória de Deus, sem passar pela corrupção do túmulo. Este privilégio único e extraordinário foi concedido a Maria em vista de sua Imaculada Conceição (preservação do pecado original), de sua maternidade divina (Mãe de Deus) e de sua virgindade perpétua. Em 1º de novembro de 1950, o Papa Pio XII, após consultar todos os bispos do mundo e invocar a infalibilidade pontifícia, proclamou solenemente este dogma na Constituição Apostólica 'Munificentissimus Deus', declarando: 'A Imaculada Mãe de Deus, sempre Virgem Maria, terminado o curso da vida terrestre, foi assunta em corpo e alma à glória celeste'. A Assunção é celebrada desde os primórdios da Igreja, sendo uma das festas marianas mais antigas, importantes e universais, remontando ao século VI no Oriente e ao século VII no Ocidente. A tradição apostólica sempre afirmou que Maria, após sua 'dormição' (koimesis), foi elevada ao Céu. Este mistério glorioso nos ensina que Maria, preservada do pecado original desde sua conceição e tendo cooperado plenamente e de modo único com a obra redentora de Cristo, foi também preservada da corrupção do túmulo que é consequência do pecado. A Assunção de Maria antecipa e prefigura a ressurreição da carne prometida a todos os fiéis no fim dos tempos, e nos dá esperança e certeza de que também nós, se permanecermos fiéis a Cristo, participaremos da glória celeste em corpo e alma. Maria, assunta ao Céu e coroada Rainha do Céu e da Terra, intercede constantemente por nós junto a seu Filho Jesus Cristo, nosso único Mediador e Salvador. A festa da Assunção, em 15 de agosto, é celebrada com grande solenidade em todo o mundo católico, sendo feriado religioso em muitos países." },
        { id: "rainha", name: "Nossa Senhora Rainha", date: "22/08", month: "Agosto", imageUrl: "/images/ns_rainha.png", description: "Oitava da Assunção, celebrando a realeza de Maria", fullDescription: "A festa de Nossa Senhora Rainha foi instituída pelo Papa Pio XII em 1954, celebrada originalmente em 31 de maio e transferida para 22 de agosto pelo Papa Paulo VI em 1969, oito dias após a Assunção. Maria é Rainha porque é Mãe do Rei dos reis, Jesus Cristo. Sua realeza não é de poder mundano, mas de amor, serviço e intercessação. Como Rainha do Céu e da Terra, Maria reina sobre todos os corações que a amam e sobre toda a criação. Ela é coroada com doze estrelas, como descrito no Apocalipse, simbolizando sua glória e seu papel único na história da salvação. Celebrar Maria como Rainha é reconhecer sua dignidade suprema entre todas as criaturas e sua participação especial no reino de seu Filho." },

        // SETEMBRO
        { id: "natividade", name: "Natividade de Nossa Senhora", date: "08/09", month: "Setembro", imageUrl: "/images/ns_natividade.png", description: "O aniversário de Maria. Também Nossa Senhora da Luz", fullDescription: "A Natividade de Nossa Senhora, celebrada em 8 de setembro, é uma das festas marianas mais antigas da Igreja, remontando ao século VI. Embora a data exata do nascimento de Maria não seja conhecida, a tradição fixou esta data nove meses após a festa da Imaculada Conceição (8 de dezembro). O nascimento de Maria foi um evento de imensa alegria para toda a humanidade, pois ela seria a Mãe do Salvador. Filha de Sant'Ana e São Joaquim, Maria nasceu em Jerusalém, livre do pecado original, preparada por Deus desde o primeiro instante de sua existência para ser o tabernáculo vivo do Verbo Encarnado. Esta festa nos convida a contemplar o plano divino de salvação que começou a se manifestar com o nascimento da Virgem Maria." },
        { id: "dores", name: "Nossa Senhora das Dores", date: "15/09", month: "Setembro", imageUrl: "/images/ns_dores_setembro.png", description: "Memória oficial. Padroeira de Minas Gerais", fullDescription: "A festa de Nossa Senhora das Dores, celebrada em 15 de setembro (dia seguinte à Exaltação da Santa Cruz), nos convida a contemplar os sofrimentos de Maria ao longo de sua vida, especialmente ao pé da Cruz de seu Filho. A tradição católica enumera as Sete Dores de Maria: a profecia de Simeão, a fuga para o Egito, a perda de Jesus no templo, o encontro com Jesus no caminho do Calvário, a crucificação, a descida da cruz e o sepultamento de Jesus. Maria é padroeira de Minas Gerais e modelo de fé e fortaleza no sofrimento. Sua dor maternal não foi estéril, mas cooperou com a obra redentora de Cristo. Ao contemplar as dores de Maria, aprendemos a unir nossos sofrimentos aos de Cristo e de sua Mãe, transformando-os em fonte de graça e salvação." },
        { id: "piedade", name: "Nossa Senhora da Piedade (Pietá)", date: "15/09", month: "Setembro", imageUrl: "https://iili.io/fjEOxIV.jpg", description: "Padroeira de Minas Gerais. Invocada em sua imagem com Jesus morto nos braços (Pietà).", fullDescription: "A imagem da Pietà (palavra italiana que significa 'piedade' ou 'compaixão') representa Maria segurando o corpo de Jesus após a descida da cruz. Esta representação artística, imortalizada pela escultura de Michelangelo no Vaticano, expressa a dor maternal de Maria e sua participação no mistério da redenção. Nossa Senhora da Piedade é padroeira de Minas Gerais, sendo venerada especialmente no Santuário de Congonhas. A devoção nos ensina a contemplar o amor sacrificial de Cristo e a compaixão de Maria, que acolhe em seus braços maternos não apenas o corpo de seu Filho, mas todos os que sofrem. É invocada por aqueles que passam por momentos de dor, luto e sofrimento, oferecendo consolo e esperança." },
        { id: "la_salette", name: "Nossa Senhora de La Salette", date: "19/09", month: "Setembro", imageUrl: "/images/ns_la_salette.png", description: "Aparição aprovada (França), devoção 'reconciliadora'", fullDescription: "Em 19 de setembro de 1846, Nossa Senhora apareceu a dois pastorzinhos, Mélanie Calvat e Maximin Giraud, nos Alpes franceses, perto da aldeia de La Salette. Maria apareceu chorando, sentada sobre uma pedra, com uma coroa de rosas e um crucifixo no peito cercado de ferramentas (martelo e tenazes), simbolizando os instrumentos da Paixão. Ela lamentou a frieza religiosa do povo, a profanação do domingo e a blasfêmia, pedindo conversão e penitência. A aparição foi reconhecida pela Igreja em 1851. Nossa Senhora de La Salette é conhecida como a 'Reconciliadora dos Pecadores', convidando-nos à conversão do coração e à reconciliação com Deus. Suas lágrimas expressam a dor maternal pelos filhos que se afastam de Deus." },
        { id: "merces", name: "Nossa Senhora das Mercês", date: "24/09", month: "Setembro", imageUrl: "/images/ns_merces.png", description: "Ordem Mercedária, libertação dos cativos", fullDescription: "A devoção a Nossa Senhora das Mercês (ou da Mercé) tem origem em uma aparição de Maria a São Pedro Nolasco em Barcelona, Espanha, em 1218. Maria pediu a fundação de uma ordem religiosa dedicada à redenção dos cristãos cativos pelos mouros. Assim nasceu a Ordem dos Mercedários, cujos membros faziam um quarto voto: permanecer como reféns se necessário para libertar os cativos. A imagem mostra Maria com o Menino Jesus, ambos segurando correntes quebradas, símbolo da libertação. Hoje, Nossa Senhora das Mercês é invocada não apenas para a libertação física, mas especialmente para a libertação espiritual do pecado e de todas as escravidões que aprisionam o coração humano. É padroeira de Barcelona e muito venerada na América Latina." },
        { id: "desatadora", name: "Nossa Senhora Desatadora dos Nós", date: "28/09", month: "Setembro", imageUrl: "/images/ns_desatadora.png", description: "Devoção alemã que explodiu no Brasil nos anos 2000. O dia 28 é o dia mensal de devoção.", fullDescription: "A devoção a Nossa Senhora Desatadora dos Nós tem origem em uma pintura de 1700, do artista Johann Georg Melchior Schmidtner, que se encontra na igreja de St. Peter am Perlach, em Augsburgo, Alemanha. A imagem mostra Maria desatando nós de uma fita branca, simbolizando os problemas, angústias e dificuldades que amarram nossa vida. A devoção foi trazida ao Brasil e Argentina nos anos 1990 e se espalhou rapidamente, especialmente após o Papa Francisco (então Cardeal Bergoglio) promovê-la em Buenos Aires. Maria é invocada para desatar os 'nós' de nossas vidas: problemas familiares, doenças, vícios, angústias, conflitos. O dia 28 de cada mês é dedicado a esta devoção, sendo 28 de setembro a festa principal. A devoção nos ensina a confiar em Maria como medianeira que leva nossos problemas a Jesus." },

        // OUTUBRO
        { id: "rosario", name: "Nossa Senhora do Rosário", date: "07/10", month: "Outubro", imageUrl: "https://i.postimg.cc/2669v1gr/nsr.jpg", description: "Memória do terço e vitória de Lepanto", fullDescription: "A devoção a Nossa Senhora do Rosário remonta ao século XIII, ligada a São Domingos de Gusmão. A festa de 7 de outubro comemora a Vitória de Lepanto (1571), atribuída à intercessão da Virgem através do Rosário. Em Pompeia, Itália, o Beato Bartolo Longo construiu um grande santuário e se tornou o 'Apóstolo do Rosário'." },
        { id: "aparecida", name: "Nossa Senhora Aparecida", date: "12/10", month: "Outubro", imageUrl: "https://i.postimg.cc/Lsyj4XMh/4011bde1376c5422265a41f3a652c540.jpg", description: "Solenidade. Padroeira e Rainha do Brasil", fullDescription: "Em outubro de 1717, pescadores encontraram nas águas do Rio Paraíba uma imagem de Nossa Senhora da Conceição. Após o achado, a pesca foi abundante. Declarada Padroeira do Brasil em 1930, seu santuário é o segundo maior do mundo, recebendo milhões de peregrinos anualmente." },
        { id: "pilar", name: "Nossa Senhora do Pilar", date: "12/10", month: "Outubro", imageUrl: "/images/ns_pilar.png", description: "Celebra a primeira aparição de Maria na história (em vida mortal), ao Apóstolo Tiago na Espanha.", fullDescription: "Nossa Senhora do Pilar é venerada como a primeira aparição de Maria ainda em vida mortal. Segundo a tradição, no ano 40 d.C., o Apóstolo Tiago estava evangelizando na Espanha, às margens do rio Ebro, em Saragossa, quando Maria lhe apareceu sobre um pilar (coluna) de jaspe, ainda vivendo em Jerusalém. Ela pediu que construísse ali uma capela em sua honra. O pilar permanece até hoje na Basílica de Nossa Senhora do Pilar, em Saragossa, sendo um dos santuários marianos mais antigos do mundo. Maria é invocada como 'do Pilar' porque apareceu sobre esta coluna, símbolo da firmeza da fé e da presença maternal de Maria na evangelização. É padroeira da Espanha e da Hispanidade, sendo celebrada com grande solenidade em 12 de outubro. A devoção se espalhou por toda a América Latina, especialmente entre os povos de língua espanhola." },
        { id: "schoenstatt", name: "Mãe Rainha de Schoenstatt", date: "18/10", month: "Outubro", imageUrl: "https://iili.io/fjEnRUl.jpg", description: "A 'Mãe Peregrina' que visita as casas (Schoenstatt). O dia 18 celebra a Aliança de Amor.", fullDescription: "O Movimento de Schoenstatt foi fundado pelo Padre José Kentenich em 1914, na Alemanha. Em 18 de outubro de 1914, na pequena capela de Schoenstatt, foi selada a 'Aliança de Amor' com Maria, quando o Padre Kentenich e seus jovens se consagraram à Mãe de Deus, pedindo que ela fizesse daquele lugar um santuário de graças. Maria aceitou este convite e Schoenstatt tornou-se um centro de renovação espiritual. A devoção à Mãe Rainha de Schoenstatt se caracteriza pela 'Mãe Peregrina' - réplicas da imagem original que visitam as casas das famílias, levando a presença maternal de Maria aos lares. O dia 18 de outubro celebra esta Aliança de Amor, um pacto de fé, confiança e entrega total a Maria. O movimento se espalhou pelo mundo todo, com milhares de santuários filiais. A espiritualidade de Schoenstatt enfatiza a vinculação pessoal com Maria, a educação para a liberdade interior e o compromisso de transformação do mundo." },
        { id: "nazare", name: "Nossa Senhora de Nazaré", date: "2º Domingo", month: "Outubro", imageUrl: "/images/ns_nazare.jpg", description: "Círio de Nazaré (Belém/PA), maior manifestação católica do Brasil", fullDescription: "Nossa Senhora de Nazaré é a padroeira do Estado do Pará e protagonista da maior manifestação religiosa católica do Brasil: o Círio de Nazaré, realizado anualmente no segundo domingo de outubro em Belém. A devoção começou em 1700, quando o caboclo Plácido encontrou uma pequena imagem de Nossa Senhora nas margens do igarapé Murutucu. Por mais que tentasse levá-la para casa, a imagem sempre retornava ao local do achado, até que foi construída uma capela no lugar. O Círio (do latim 'cereus', vela) reúne milhões de fiéis que acompanham a procissão pelas ruas de Belém, numa demonstração impressionante de fé e devoção popular. A corda do Círio, com centenas de metros, simboliza a união dos fiéis com Maria. A Basílica Santuário de Nazaré é um dos principais centros de peregrinação do Brasil, recebendo devotos de todo o país durante todo o ano, especialmente no mês de outubro, dedicado a Nossa Senhora." },

        // NOVEMBRO
        { id: "medianeira", name: "N.S. Medianeira de Todas as Graças", date: "08/11", month: "Novembro", imageUrl: "/images/ns_medianeira.png", description: "Padroeira do Rio Grande do Sul. Título teológico profundo que afirma que todas as graças passam pelas mãos de Maria.", fullDescription: "O título de 'Medianeira de Todas as Graças' expressa uma verdade teológica profunda: Maria, por sua participação única na obra da redenção, é canal através do qual todas as graças divinas chegam até nós. Este título foi especialmente promovido por São Luís Maria Grignion de Montfort e pelos Papas Leão XIII e Pio X. Nossa Senhora Medianeira é padroeira do Rio Grande do Sul desde 1930. A devoção enfatiza que Maria não é fonte das graças (que é Deus), mas a medianeira que intercede por nós e distribui os tesouros divinos. Como Mãe de Jesus e Mãe nossa, ela está sempre pronta a levar nossas necessidades ao Coração de seu Filho. A festa, celebrada em 8 de novembro, nos convida a reconhecer o papel maternal de Maria na economia da salvação e a recorrer a ela com confiança filial em todas as nossas necessidades." },
        { id: "divina_providencia", name: "Nossa Senhora da Divina Providência", date: "16/11", month: "Novembro", imageUrl: "/images/ns_divina_providencia.png", description: "Padroeira dos Padres Barnabitas. A imagem é famosa por Maria segurar a mão do Menino Jesus, que aponta para a 'providência'.", fullDescription: "A devoção a Nossa Senhora da Divina Providência tem origem em uma imagem venerada em Arezzo, Itália, desde o século XIII. A imagem mostra Maria segurando delicadamente a mão do Menino Jesus, que aponta para o alto, simbolizando a Divina Providência que cuida de todas as nossas necessidades. A devoção foi especialmente promovida pelos Padres Barnabitas, que a escolheram como padroeira. Maria, sob este título, é invocada como aquela que nos ensina a confiar na Providência divina, que nunca abandona seus filhos. Ela nos lembra que Deus conhece todas as nossas necessidades e cuida de nós com amor paternal. A festa, celebrada em 16 de novembro, nos convida a abandonar as preocupações excessivas e a confiar plenamente em Deus, seguindo o exemplo de Maria, que sempre se entregou totalmente à vontade divina." },
        { id: "apresentacao", name: "Apresentação de Nossa Senhora", date: "21/11", month: "Novembro", imageUrl: "https://i.postimg.cc/3Js86PzK/image.png", description: "Memória da entrega de Maria ao templo quando criança", fullDescription: "A festa da Apresentação de Nossa Senhora, celebrada em 21 de novembro, comemora a tradição de que Maria, ainda criança, foi levada por seus pais, Sant'Ana e São Joaquim, ao Templo de Jerusalém para ser consagrada a Deus. Segundo o Protoevangelho de Tiago, aos três anos de idade, Maria subiu sozinha os quinze degraus do Templo, demonstrando sua prontidão em servir a Deus. Ela permaneceu no Templo até a adolescência, dedicando-se à oração e ao estudo das Escrituras. Esta festa, celebrada no Oriente desde o século VI e no Ocidente desde o século XIV, nos ensina o valor da consagração total a Deus desde a infância. Maria é modelo de entrega generosa e de vida dedicada ao serviço divino. A festa nos convida a renovar nossa própria consagração a Deus e a imitar a pureza e a piedade de Maria." },
        { id: "saude", name: "Nossa Senhora da Saúde", date: "21/11", month: "Novembro", imageUrl: "https://i.postimg.cc/RCdhqSqh/image.png", description: "Invocada como protetora da saúde física e espiritual", fullDescription: "Nossa Senhora da Saúde é invocada como 'Saúde dos Enfermos', título presente na Ladainha de Nossa Senhora. Esta devoção tem raízes profundas na história da Igreja, sendo especialmente venerada em momentos de epidemias e doenças. Maria é reconhecida como aquela que intercede pela saúde física e, principalmente, pela saúde espiritual de seus filhos. Muitos santuários dedicados a Nossa Senhora da Saúde foram construídos ao longo dos séculos, especialmente no Brasil colonial, onde a devoção se espalhou rapidamente. Maria, como Mãe amorosa, acolhe todos os que sofrem de enfermidades e leva suas súplicas a Jesus, o Divino Médico. A devoção nos ensina a confiar na providência divina em tempos de doença, a aceitar o sofrimento com resignação cristã e a buscar em Maria o conforto maternal que alivia nossas dores." },
        { id: "gracas", name: "Nossa Senhora das Graças", date: "27/11", month: "Novembro", imageUrl: "https://i.postimg.cc/SsBDK7HJ/Design-sem-nome-2.png", description: "Medalha Milagrosa. Extremamente popular", fullDescription: "Em 1830, Nossa Senhora apareceu a Santa Catarina Labouré em Paris, mostrando o desenho da Medalha Milagrosa. Maria prometeu grandes graças aos que a usassem com fé. Milhões de conversões e milagres foram atribuídos a esta medalha." },

        // DEZEMBRO
        { id: "imaculada", name: "Imaculada Conceição", date: "08/12", month: "Dezembro", imageUrl: "https://iili.io/KpAtISf.png", description: "Solenidade (Dogma). Padroeira de Portugal", fullDescription: "Em 8 de dezembro de 1854, o Papa Pio IX proclamou o dogma da Imaculada Conceição, declarando que Maria foi preservada do pecado original desde o primeiro instante de sua concepção. Este privilégio único foi concedido em vista dos méritos de Jesus Cristo." },
        { id: "loreto", name: "Nossa Senhora de Loreto", date: "10/12", month: "Dezembro", imageUrl: "/images/nossa_senhora_loreto.png", description: "Padroeira da aviação e das casas", fullDescription: "A Santa Casa de Loreto, na Itália, é venerada como a casa onde a Sagrada Família viveu em Nazaré. Segundo a tradição, foi miraculosamente transportada por anjos em 1291 para protegê-la da profanação." },
        { id: "guadalupe", name: "Nossa Senhora de Guadalupe", date: "12/12", month: "Dezembro", imageUrl: "https://iili.io/ffgFDXV.png", description: "Padroeira da América Latina", fullDescription: "Em 1531, a Virgem Maria apareceu a Juan Diego no México, deixando sua imagem milagrosamente impressa em seu manto (tilma). A imagem permanece inexplicável pela ciência. Esta aparição levou à conversão de milhões de indígenas e é símbolo da evangelização das Américas." },
        { id: "boa_viagem", name: "Nossa Senhora da Boa Viagem", date: "12/12", month: "Dezembro", imageUrl: "/images/ns_boa_viagem.png", description: "Padroeira de Belo Horizonte e dos navegantes portugueses.", fullDescription: "Nossa Senhora da Boa Viagem é uma das devoções marianas mais antigas de Portugal, remontando à época dos Descobrimentos. Os navegantes portugueses levavam imagens de Nossa Senhora em suas caravelas, invocando sua proteção durante as perigosas viagens marítimas. A devoção se espalhou por todo o império português, chegando ao Brasil onde se enraizou profundamente. É padroeira de Belo Horizonte, capital de Minas Gerais, e de muitas cidades litorâneas. Maria é invocada não apenas para proteção nas viagens físicas, mas também na jornada espiritual da vida. Ela é a estrela que guia os navegantes, a mãe que protege seus filhos em todos os caminhos. A devoção nos ensina a confiar na proteção maternal de Maria em todas as circunstâncias da vida, especialmente nos momentos de incerteza e perigo." },
        { id: "expectacao", name: "Nossa Senhora do Bom Parto", date: "18/12", month: "Dezembro", imageUrl: "https://i.pinimg.com/1200x/cc/80/b9/cc80b9f6815e1ec29ad8815d63103fbb.jpg", description: "Celebrando a gravidez de Maria prestes a dar à luz", fullDescription: "A festa de Nossa Senhora do Bom Parto, também conhecida como Nossa Senhora da Expectação ou Nossa Senhora do Ó, é celebrada em 18 de dezembro, uma semana antes do Natal. Esta devoção contempla Maria grávida, nos últimos dias antes do nascimento de Jesus, vivendo a expectativa do parto. O nome 'Nossa Senhora do Ó' vem das antífonas do Advento que começam com 'Ó' (como 'Ó Sapientia', 'Ó Adonai'), rezadas nos sete dias que antecedem o Natal. Maria é especialmente invocada por mulheres grávidas, pedindo proteção durante a gestação e um parto seguro. A devoção nos convida a contemplar o mistério da Encarnação: Deus se fazendo criança no ventre de Maria. Ela nos ensina a viver a expectativa da vinda de Cristo com a mesma fé e amor com que Maria aguardava o nascimento de seu Filho." },
        { id: "nss_coracao", name: "Nossa Senhora do Sagrado Coração", date: "27/12", month: "Dezembro", imageUrl: "/images/ns_sagrado_coracao.png", description: "Advogada das causas difíceis e desesperadas.", fullDescription: "Nossa Senhora do Sagrado Coração é uma devoção que une o Coração Imaculado de Maria ao Sagrado Coração de Jesus. A imagem mostra Maria apontando para o Coração de Jesus, indicando que todas as graças vêm dele e que ela é a medianeira que nos conduz ao seu Filho. Esta devoção foi especialmente promovida pelos Padres do Sagrado Coração de Jesus (Dehonianos) e pelos Missioneiros do Sagrado Coração (MSC). Maria é invocada como 'Advogada das Causas Difíceis e Desesperadas', sendo especialmente procurada por aqueles que enfrentam situações humanamente impossíveis. A devoção nos ensina que o Coração de Maria está intimamente unido ao Coração de Jesus, e que recorrendo a ela, encontramos o caminho seguro para alcançar as graças do Coração de seu Filho. É uma devoção de grande confiança e esperança, especialmente para aqueles que se encontram em situações desesperadoras." },
    ];

    const months = ["Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"];

    const devotionsByMonth = months.map((month, index) => ({
        month,
        items: devotions.filter(d => d.month === month),
        isPink: index % 2 !== 0 // Alternating index for colors
    }));

    return (
        <section className="mb-12">
            <h2 className="text-4xl font-bold text-blue-900 dark:text-blue-100 text-center mb-10 font-brand">
                🌹 Galeria de Devoções Marianas 🌹
            </h2>

            <div className="space-y-12">
                {devotionsByMonth.map(({ month, items, isPink }) => (
                    items.length > 0 && (
                        <div
                            key={month}
                            className={`p-8 rounded-3xl shadow-lg border transition-all duration-500 ${isPink
                                ? 'bg-gradient-to-br from-pink-50 to-rose-50 border-pink-100 dark:from-pink-950/20 dark:to-rose-950/20 dark:border-pink-900/30'
                                : 'bg-gradient-to-br from-blue-50 to-sky-50 border-blue-100 dark:from-blue-950/20 dark:to-sky-950/20 dark:border-blue-900/30'
                                }`}
                        >
                            <h3 className={`text-2xl font-bold mb-8 flex items-center gap-3 ${isPink ? 'text-pink-800 dark:text-pink-300' : 'text-blue-800 dark:text-blue-300'
                                }`}>
                                <span className="w-2 h-8 bg-current rounded-full"></span>
                                {month}
                            </h3>

                            <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-8">
                                {items.map((devotion) => (
                                    <Dialog key={devotion.id}>
                                        <DialogTrigger asChild>
                                            <div className="cursor-pointer group flex flex-col items-center">
                                                <div className="relative w-full max-w-[140px]">
                                                    <Image
                                                        src={devotion.imageUrl}
                                                        alt={devotion.name}
                                                        width={200}
                                                        height={200}
                                                        className={`aspect-square rounded-full object-cover border-4 transition-all duration-300 shadow-md group-hover:shadow-xl group-hover:scale-105 ${isPink ? 'border-pink-200 group-hover:border-pink-400' : 'border-blue-200 group-hover:border-blue-400'
                                                            }`}
                                                    />
                                                    <div className={`absolute bottom-0 left-1/2 transform -translate-x-1/2 translate-y-1/2 z-10`}>
                                                        <span className={`inline-block px-3 py-1 text-white text-[10px] font-bold rounded-full shadow-sm ${isPink ? 'bg-pink-600' : 'bg-blue-600'
                                                            }`}>
                                                            {devotion.date}
                                                        </span>
                                                    </div>
                                                </div>
                                                <p className="text-center mt-6 text-sm font-semibold text-slate-700 dark:text-slate-300 line-clamp-2 px-2 h-10 flex items-center justify-center">
                                                    {devotion.name}
                                                </p>
                                            </div>
                                        </DialogTrigger>

                                        <DevotionDialog devotion={devotion} />
                                    </Dialog>
                                ))}
                            </div>
                        </div>
                    )
                ))}
            </div>
        </section >
    );
}

// Componente helper para Dialog com scroll dinâmico
function DevotionDialog({ devotion }: { devotion: MarianDevotion }) {
    const [scrolled, setScrolled] = useState(false);
    const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
        const scrollTop = e.currentTarget.scrollTop;
        setScrolled(scrollTop > 50);
    };

    return (
        <DialogContent className="sm:max-w-3xl max-w-[98vw] max-h-[95vh] flex flex-col bg-gradient-to-br from-white to-blue-50 dark:from-slate-900 dark:to-blue-950 border-2 border-blue-200 dark:border-blue-800 shadow-2xl overflow-hidden">
            {/* Botão Voltar Estilizado */}
            <DialogClose className="absolute left-8 top-16 z-50 rounded-full bg-blue-600 hover:bg-blue-700 text-white p-2 shadow-lg transition-all hover:scale-110 focus:outline-none focus:ring-2 focus:ring-blue-500">
                <X className="h-5 w-5" />
                <span className="sr-only">Fechar</span>
            </DialogClose>

            <DialogHeader className="px-2 pt-10 pb-4 relative flex-shrink-0">
                <div className="flex flex-col items-center justify-center min-h-[160px] sm:min-h-[200px]">
                    <div className={`relative transition-all duration-500 ease-in-out ${scrolled ? 'scale-50 -translate-y-4' : 'scale-100'}`}>
                        <Image
                            src={devotion.imageUrl}
                            alt={devotion.name}
                            width={200}
                            height={200}
                            className="rounded-full object-cover border-4 border-blue-300 dark:border-blue-600 shadow-xl w-32 h-32 sm:w-40 sm:h-40"
                        />
                    </div>
                    <DialogTitle className={`font-bold text-blue-900 dark:text-blue-100 text-center font-brand px-2 break-words hyphens-auto transition-all duration-500 ease-in-out ${scrolled ? 'text-lg sm:text-xl -translate-y-8' : 'text-xl sm:text-2xl md:text-3xl mt-4'
                        }`}>
                        {devotion.name}
                    </DialogTitle>
                    <div className={`flex items-center gap-2 flex-wrap justify-center px-2 transition-all duration-500 ease-in-out ${scrolled ? 'opacity-0 scale-95 pointer-events-none h-0 mt-0' : 'opacity-100 mt-2'
                        }`}>
                        <span className="px-3 py-1 bg-blue-100 dark:bg-blue-900/50 text-blue-700 dark:text-blue-300 text-sm font-bold rounded-full">
                            {devotion.date}
                        </span>
                        <span className="text-slate-400">•</span>
                        <span className="text-slate-600 dark:text-slate-400 font-medium">
                            {devotion.month}
                        </span>
                    </div>
                </div>
            </DialogHeader>

            <div
                className="flex-1 overflow-y-auto px-3 sm:px-6 custom-scrollbar scroll-smooth"
                onScroll={handleScroll}
            >
                <div className="space-y-6 pb-24 animate-in fade-in duration-700">
                    <div className="bg-blue-50/50 dark:bg-blue-900/10 p-4 sm:p-6 rounded-2xl border border-blue-100 dark:border-blue-900/20">
                        <p className="text-slate-700 dark:text-slate-300 leading-relaxed text-center italic text-sm sm:text-base break-words">
                            "{devotion.description}"
                        </p>
                    </div>

                    {devotion.fullDescription && (
                        <div className="space-y-3 animate-in fade-in slide-in-from-bottom-4 duration-500">
                            <h4 className="text-lg font-bold text-blue-800 dark:text-blue-200 flex items-center gap-2 px-1">
                                <BookOpen className="w-5 h-5 flex-shrink-0" />
                                História e Significado
                            </h4>
                            <p className="text-slate-700 dark:text-slate-300 leading-relaxed px-1 text-sm sm:text-base break-words whitespace-pre-wrap">
                                {devotion.fullDescription}
                            </p>
                        </div>
                    )}

                    {devotion.novenaId && (
                        <div className="bg-green-50 dark:bg-green-900/20 p-4 rounded-xl border border-green-100 dark:border-green-900/30 flex items-center gap-3 animate-in fade-in slide-in-from-bottom-4 duration-700">
                            <div className="w-10 h-10 bg-green-100 dark:bg-green-900/50 rounded-full flex items-center justify-center flex-shrink-0">
                                <span className="text-xl">✨</span>
                            </div>
                            <p className="text-sm text-green-800 dark:text-green-200 font-semibold break-words">
                                Esta devoção possui novena disponível em nosso site!
                            </p>
                        </div>
                    )}
                </div>
            </div>
        </DialogContent>
    );
}
