const fs = require('fs');
let data = fs.readFileSync('src/lib/novenas-fev-set.ts', 'utf8');

const novenaContent = `
  sao_joao_vianney: {
    title: 'Novena a São João Maria Vianney',
    description: "Novena em honra ao Santo Cura d'Ars, padroeiro dos párocos e modelo de amor à Eucaristia e à reconciliação.",
    initialPrayer: \`<div class="prayer-block"><h4>Apresentação</h4><p>João Maria Batista Vianney - Santo Cura d'Ars - foi um sacerdote francês. Muito antes de ser canonizado pelo papa Pio XI, em 1925, já era venerado como santo. O seu corpo incorrupto, encontra-se na igreja da paróquia de Ars, que se tornou um grande santuário de peregrinação. São João Maria Batista Vianney foi proclamado pelo Papa Pio XI Padroeiro dos Párocos e dos Sacerdotes que têm Cura de Almas no mundo todo, por Carta Apostólica datada de 20 de abril de 1929. Devido o seu exemplo de pastor, associa-se informalmente à sua memória, em 04 de agosto, a comemoração do dia do Padre. Foi um grande confessor, tinha o dom da profecia, recebia ataques físicos do demônio e viveu entregue à mortificação e à oração.</p></div>\`,
    finalPrayer: \`<div class="prayer-block"><h4 class="section-title">Oração Final Diária</h4><p>Ó Santo Cura d’Ars, tenho confiança em vossa intercessão. Intercedei especialmente por mim durante esta novena.</p><p class="italic">(pedir a graça desejada)</p><p class="mt-4 font-semibold">Reza-se: Pai-Nosso, Ave Maria, Glória ao Pai.</p><p class="mt-2 font-bold">São João Maria Vianney, rogai por nós!</p></div>\`,
    days: [
      { day: 'Primeiro Dia', title: 'Fé Ardente', content: '<div class="day-specific-content"><p>Ó São João Maria Vianney, vós nascestes de uma mãe profundamente cristã e dela recebestes, juntamente com a fé, o amor de Deus e da oração. Pequenino ainda, éreis surpreendido de joelhos diante da imagem de Nossa Senhora. Vossa alma era naturalmente atraída para as coisas do alto. No entanto, quanto vos custou quando tivestes que corresponder à vossa vocação! Quantos obstáculos e contradições da parte dos homens! E depois, quanto lutastes e sofrestes para chegardes a ser o Sacerdote perfeito que fostes! Mas, vosso espírito de fé tão profundo vos sustentou em todos vossos combates.</p><p>Ó grande Santo, vós conheceis os desejos de minha alma: eu gostaria de melhor servir ao Deus do qual já recebi tantos favores. Para isso, obtende-me mais coragem e, sobretudo, mais espírito de fé. Muitos dos meus pensamentos, palavras e ações são inúteis para minha santificação e salvação, pois esse espírito sobrenatural ainda não anima minha vida. Fazei que isso mude de agora em diante.</p></div>' },
      { day: 'Segundo Dia', title: 'Esperança', content: '<div class="day-specific-content"><p>Ó São João Maria Vianney, que confiança tinham as multidões em vossas orações! Vós não podíeis sair de vossa casa paroquial ou de vossa pobre igreja sem estardes cercado de almas suplicantes que se dirigiam a vós, do mesmo modo como se dirigiriam ao próprio Jesus em Sua vida mortal. E vós, bom Santo, por vossas palavras cheias de eternidade, as excitáveis à esperança. Vós que sempre confiastes inteiramente no Coração de Deus, obtende-me uma confiança profunda e filial em Sua adorável Providência. Que a esperança nos bens celestes encha meu coração de coragem e me ajude a praticar sempre os divinos mandamentos.</p></div>' },
      { day: 'Terceiro Dia', title: 'Caridade', content: '<div class="day-specific-content"><p>Ó São João Maria Vianney, quão grande foi a caridade da qual fizestes prova a Deus e ao próximo. Não podíeis pregar sobre o amor de Deus sem derramar ardentes lágrimas e, em vossos últimos anos, parecia que não podíeis falar de outra coisa, nem viver para outra coisa. Quanto ao próximo, para o consolar, absolver e santificar, vós vos sacrificastes até o extremo limite de vossas forças. Herói da caridade, inspirai-me um maior amor de Deus, amor que se exprima mais por atos do que por palavras. Concedei-me amar a meu próximo generosa e cristãmente.</p></div>' },
      { day: 'Quarto Dia', title: 'Contrição dos Pecados', content: '<div class="day-specific-content"><p>Ó São João Maria Vianney, que fostes sempre duro contra o pecado, mas sempre acolhedor e compassivo para com o pecador, eu venho a vós como se ainda vivêsseis, como se pudésseis me atender ajoelhado aos vossos pés. Inclinado a mim, vós escutais a confidência arrependida das minhas fraquezas e misérias. Sacerdote do Senhor, confessor infatigável, se isso não é nada mais que um sonho do meu coração, obtende-me pelo menos o horror ao pecado. Vós queríeis que em primeiro lugar se evitassem as ocasiões perigosas. Tomarei, sob vosso conselho, a resolução de romper com todos os hábitos repreensíveis e más ocasiões. Ajudai-me hoje a examinar minha consciência.</p></div>' },
      { day: 'Quinto Dia', title: 'Hábito da Confissão Frequente', content: '<div class="day-specific-content"><p>Ó São João Maria Vianney, vós sabeis que importância tem, na vida do cristão, uma confissão bem feita. Foi para buscar os felizes frutos da confissão para milhões de almas, que consentistes em ficar durante dezesseis horas por dia como que prisioneiro, sem ar e sem luz, entre as rudes madeiras de um confessionário. Ah! Eu percebo que, se tomo o excelente hábito da confissão frequente, se me preparo bem, se tenho sempre um arrependimento suficiente de minhas faltas, não somente minha perseverança final, mas a santificação da minha alma está assegurada. Pedi por mim esta graça.</p></div>' },
      { day: 'Sexto Dia', title: 'Devoção à Santa Missa e à Comunhão', content: '<div class="day-specific-content"><p>Ó São João Maria Vianney, cujo grande e, frequentemente, único conforto nesse mundo miserável foi a presença real de Jesus no sacrário, vossa grande alegria não era a de distribuir a Comunhão aos peregrinos que vos visitavam? Vós afastáveis da Santa Mesa as almas que recusavam a corrigir-se, mas às almas de boa vontade, abríeis de par em par as portas do festim eucarístico. Ó grande Santo, que cada dia na Santa Missa, comungastes com o ardor de um Serafim, concedei-me um pouco do vosso fervor. Com a graça de ter a alma limpa de qualquer pecado mortal, obtende-me o desejo sincero de aproveitar da comunhão, desta visita divina que embalsamava vosso coração.</p></div>' },
      { day: 'Sétimo Dia', title: 'Vida de Oração', content: '<div class="day-specific-content"><p>Ó São João Maria Vianney, tornaram-se célebres os ataques infernais que tivestes de suportar. Para fazer-vos sucumbir ante a fadiga, de modo a abandonardes vossa missão sublime de convertedor, o demônio veio perturbar durante longos anos o curto repouso de vossas noites. Mas, vós o vencestes pela mortificação e oração. Ó poderoso Protetor, vós sabeis que o tentador deseja-me o mal e que ele odeia minha alma batizada e crente. Ele quer fazer-me cair no pecado para que eu perca o gosto pela virtude e pelos sacramentos. Mas, bom Santo de Ars, vós afastareis de mim as armadilhas do inimigo.</p></div>' },
      { day: 'Oitavo Dia', title: 'Prática da Santa Pureza', content: '<div class="day-specific-content"><p>Ó São João Maria Vianney, uma testemunha de vossa vida, edificado pela modéstia e delicada pureza que se irradiavam de toda a vossa pessoa, fez de vós este magnífico elogio: “Parecia um anjo em carne mortal”. Com que atratividade e entusiasmo pregastes aos fiéis estas belas virtudes, cujo perfume, dizíeis, “assemelha-se ao de uma vinha em flor”. Eu vos peço, uni vossa intercessão à de Maria Imaculada e à de vossa cara e pequena Santa Filomena a fim de que eu guarde sempre, como Deus pede de mim, a pureza do meu coração. Vós que dirigistes tantas almas ao cume das virtudes, defendei-me contra as tentações e obtende-me a graça de sempre vencê-las.</p></div>' },
      { day: 'Nono Dia', title: 'Perseverança na Graça de Deus', content: '<div class="day-specific-content"><p>Ó São João Maria Vianney, vossos preciosos restos mortais repousam hoje em um magnífico relicário, presente dos padres da França. E essa glória terrena nada mais é do que uma pálida imagem da glória inefável que gozais junto de Deus. Durante vossa vida aqui na terra, nas horas de fadiga costumáveis dizer: “Descansaremos na outra vida!” É a realidade: vós estais agora na paz eterna, na eterna felicidade. Ah! Como eu desejo seguir-vos um dia. Desde o céu vos ouço dizer-me: “É necessário trabalhar e lutar enquanto se está neste mundo”. Ensinai-me, portanto, a trabalhar na salvação da minha alma, a dar o bom conselho e o bom exemplo, a fazer o bem em redor de mim, a fim de que tenha parte, como vós, na felicidade dos Eleitos.</p></div>' }
    ]
  },
`;

const insertIndex = data.lastIndexOf('};');
data = data.slice(0, insertIndex) + novenaContent + data.slice(insertIndex);

fs.writeFileSync('src/lib/novenas-fev-set.ts', data);
